### ISSUE TITLE
IDE Fatal Errors

### ISSUE THREAD

**Issue by Pollizzio** [groboclown/p4ic4idea#113]
Plugin 0.7.8, Studio 1.5.1, I have the following IDE fatal error when the plugin is active, side effect is the project loading stuck and fails:

null
java.lang.NullPointerException
	at com.intellij.openapi.vcs.VcsActiveEnvironmentsProxy.proxyVcs(VcsActiveEnvironmentsProxy.java:34)
	at com.intellij.openapi.vcs.impl.VcsEP.getVcs(VcsEP.java:64)
	at com.intellij.openapi.vcs.impl.projectlevelman.AllVcses.getByName(AllVcses.java:103)
	at com.intellij.openapi.vcs.impl.ProjectLevelVcsManagerImpl.getVcsFor(ProjectLevelVcsManagerImpl.java:293)
	at com.intellij.openapi.vcs.changes.VcsGuess.getVcsForDirty(VcsGuess.java:65)
	at com.intellij.openapi.vcs.changes.VcsDirtyScopeManagerImpl$5.run(VcsDirtyScopeManagerImpl.java:154)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
	at com.intellij.openapi.vcs.changes.VcsDirtyScopeManagerImpl.convertPaths(VcsDirtyScopeManagerImpl.java:151)
	at com.intellij.openapi.vcs.changes.VcsDirtyScopeManagerImpl.filePathsDirty(VcsDirtyScopeManagerImpl.java:169)
	at com.intellij.openapi.vcs.changes.VcsDirtyScopeVfsListener$FileAndDirsCollector.markDirty(VcsDirtyScopeVfsListener.java:251)
	at com.intellij.openapi.vcs.changes.VcsDirtyScopeVfsListener$FileAndDirsCollector.access$300(VcsDirtyScopeVfsListener.java:196)
	at com.intellij.openapi.vcs.changes.VcsDirtyScopeVfsListener$1.run(VcsDirtyScopeVfsListener.java:92)
	at com.intellij.openapi.util.ZipperUpdater$1.run(ZipperUpdater.java:65)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by groboclown** [comment]
Thanks for the bug report.

This is an interesting issue.  Can you check your log file?  It looks like the IDE is failing to load the Perforce class, and the log file should contain an error with the class loading problem.  My first guess is that the plugin needs to be re-downloaded, and my second guess is that there's a class loading dependency error).

As background, the "VcsEP" class is the extension point used by the plugin to declare a VCS provider class.  This particular failure looks to be caused by the VcsEP class not able to find the class file.

**Comment by Pollizzio** [comment]
I uninstalled and installed again the plugin but had the same issue. PFA the IDE log, if It's this the log you meant. Thanks
[idea.log.zip](https://github.com/groboclown/p4ic4idea/files/186335/idea.log.zip)

**Comment by groboclown** [comment]
Thanks very much for the log file.  It looks like the plugin was loading the version-specific extensions (as it should), but it failed when it tried loading the IDEA 16 version of those, which now seems obvious.

```
2016-03-23 16:50:08,268 [  51684]  ERROR - ntellij.openapi.vcs.impl.VcsEP - net/groboclown/idea/p4ic/compat/idea160/CompatFactory160 : Unsupported major.minor version 52.0 [Plugin: PerforceIC] 
com.intellij.diagnostic.PluginException: net/groboclown/idea/p4ic/compat/idea160/CompatFactory160 : Unsupported major.minor version 52.0 [Plugin: PerforceIC]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:266)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:363)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at net.groboclown.idea.p4ic.compat.CompatFactoryLoader.loadCompatFactory(CompatFactoryLoader.java:87)
```

I should have a fix out shortly.
