### ISSUE TITLE
"Error synchronizing files" message when using the Update Project action

### ISSUE THREAD

**Issue by gridlined** [groboclown/p4ic4idea#114]
When selecting VCS --> Update Project (or the Command-T shortcut, on Mac OS), the process seems to complete properly with the tooltip appearing above the Version Control toolbar tab saying "All files are up to date" or similar. However, the Messages window opens simultaneously and displays "Error synchronizing files", under which the detail reads "Error: Failed to synchronize files with server (no error message)". Subsequent attempts to update don't always display the message (it is most common for the first attempt after starting the IDE).

I've verified that my connection configuration is correct, as it matches that which I use through P4V without any issues. I'm also running the latest version of the plugin at this time (0.7.13). My WebStorm is version 11.0.3, though that shouldn't make a difference.

**Comment by groboclown** [comment]
Thanks for the bug submission.  This issue stems from one of several problems that occurred while performing the sync operation.  Unfortunately, it looks like the underlying error didn't include a message.

Your ide log should include a warning that has the stack trace and full error message.  I don't know exactly what the option is on Mac, but the log file should be easily found through the ide Help menu -> Show log (in Windows, it's listed as "Show Log in Explorer").

Would you mind posting that error and stack trace to this bug?

**Comment by gridlined** [comment]
```
2016-04-01 08:46:57,124 [ 197847]   WARN -                             p4 - p4java error: I/O error encountered in stream command: /var/folders/st/lgw2z0ln3cx06189g70qyx657_dzhb/T/1459525426729-0/p4j4708835924159574702.tmp (No such file or directory) 
2016-04-01 08:46:57,124 [ 197847]   INFO -                             p4 - p4java error 
java.io.FileNotFoundException: /var/folders/st/lgw2z0ln3cx06189g70qyx657_dzhb/T/1459525426729-0/p4j4708835924159574702.tmp (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.perforce.p4java.impl.generic.core.TempFileInputStream.<init>(TempFileInputStream.java:27)
	at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execStreamCmd(NtsServerImpl.java:529)
	at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execStreamCmd(NtsServerImpl.java:434)
	at com.perforce.p4java.impl.mapbased.server.Server.execStreamCmd(Server.java:5033)
	at com.perforce.p4java.impl.mapbased.server.Server.getFileContents(Server.java:3214)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$32.run(P4Exec2.java:1038)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$32.run(P4Exec2.java:1027)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec$1.run(ClientExec.java:129)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunWithSkippedPasswordCheck(ServerRunner.java:201)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:137)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:129)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.p4RunFor(ClientExec.java:232)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.runWithClient(ClientExec.java:115)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.loadMd5For(P4Exec2.java:1027)
	at net.groboclown.idea.p4ic.v2.server.P4Server$32.query(P4Server.java:1336)
	at net.groboclown.idea.p4ic.v2.server.P4Server$32.query(P4Server.java:1329)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$2.perform(ServerConnection.java:194)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer$1.compute(Synchronizer.java:184)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:974)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer.runImmediateAction(Synchronizer.java:172)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.query(ServerConnection.java:189)
	at net.groboclown.idea.p4ic.v2.server.P4Server.getFilesDifferentThanServerOnline(P4Server.java:1329)
	at net.groboclown.idea.p4ic.v2.server.P4Server.getVirtualFilesDifferentThanServerHaveVersionOnline(P4Server.java:1218)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.syncChanges(P4ChangeProvider.java:210)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.getChanges(P4ChangeProvider.java:133)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.a(ChangeListManagerImpl.java:754)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.a(ChangeListManagerImpl.java:671)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.c(ChangeListManagerImpl.java:546)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.access$1600(ChangeListManagerImpl.java:74)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$ActualUpdater.run(ChangeListManagerImpl.java:451)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:264)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-04-01 08:46:57,128 [ 197851]   INFO - server.connection.ServerRunner - Request problem 
com.perforce.p4java.exception.RequestException: I/O error encountered in stream command: /var/folders/st/lgw2z0ln3cx06189g70qyx657_dzhb/T/1459525426729-0/p4j4708835924159574702.tmp (No such file or directory)
	at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execStreamCmd(NtsServerImpl.java:548)
	at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execStreamCmd(NtsServerImpl.java:434)
	at com.perforce.p4java.impl.mapbased.server.Server.execStreamCmd(Server.java:5033)
	at com.perforce.p4java.impl.mapbased.server.Server.getFileContents(Server.java:3214)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$32.run(P4Exec2.java:1038)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$32.run(P4Exec2.java:1027)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec$1.run(ClientExec.java:129)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunWithSkippedPasswordCheck(ServerRunner.java:201)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:137)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:129)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.p4RunFor(ClientExec.java:232)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.runWithClient(ClientExec.java:115)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.loadMd5For(P4Exec2.java:1027)
	at net.groboclown.idea.p4ic.v2.server.P4Server$32.query(P4Server.java:1336)
	at net.groboclown.idea.p4ic.v2.server.P4Server$32.query(P4Server.java:1329)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$2.perform(ServerConnection.java:194)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer$1.compute(Synchronizer.java:184)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:974)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer.runImmediateAction(Synchronizer.java:172)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.query(ServerConnection.java:189)
	at net.groboclown.idea.p4ic.v2.server.P4Server.getFilesDifferentThanServerOnline(P4Server.java:1329)
	at net.groboclown.idea.p4ic.v2.server.P4Server.getVirtualFilesDifferentThanServerHaveVersionOnline(P4Server.java:1218)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.syncChanges(P4ChangeProvider.java:210)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.getChanges(P4ChangeProvider.java:133)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.a(ChangeListManagerImpl.java:754)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.a(ChangeListManagerImpl.java:671)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.c(ChangeListManagerImpl.java:546)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.access$1600(ChangeListManagerImpl.java:74)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$ActualUpdater.run(ChangeListManagerImpl.java:451)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:264)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /var/folders/st/lgw2z0ln3cx06189g70qyx657_dzhb/T/1459525426729-0/p4j4708835924159574702.tmp (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.perforce.p4java.impl.generic.core.TempFileInputStream.<init>(TempFileInputStream.java:27)
	at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execStreamCmd(NtsServerImpl.java:529)
	... 36 more
2016-04-01 08:46:57,131 [ 197854]   WARN - server.connection.AlertManager - Problem reading server file file:///cobalt/perforce/Core/Websites/Hydra/trunk/platform/hydra-server/installer/pre-deploy.py 
net.groboclown.idea.p4ic.server.exceptions.P4ApiException: I/O error encountered in stream command: /var/folders/st/lgw2z0ln3cx06189g70qyx657_dzhb/T/1459525426729-0/p4j4708835924159574702.tmp (No such file or directory)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunWithSkippedPasswordCheck(ServerRunner.java:306)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:137)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:129)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.p4RunFor(ClientExec.java:232)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.runWithClient(ClientExec.java:115)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.loadMd5For(P4Exec2.java:1027)
	at net.groboclown.idea.p4ic.v2.server.P4Server$32.query(P4Server.java:1336)
	at net.groboclown.idea.p4ic.v2.server.P4Server$32.query(P4Server.java:1329)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$2.perform(ServerConnection.java:194)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer$1.compute(Synchronizer.java:184)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:974)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer.runImmediateAction(Synchronizer.java:172)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.query(ServerConnection.java:189)
	at net.groboclown.idea.p4ic.v2.server.P4Server.getFilesDifferentThanServerOnline(P4Server.java:1329)
	at net.groboclown.idea.p4ic.v2.server.P4Server.getVirtualFilesDifferentThanServerHaveVersionOnline(P4Server.java:1218)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.syncChanges(P4ChangeProvider.java:210)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.getChanges(P4ChangeProvider.java:133)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.a(ChangeListManagerImpl.java:754)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.a(ChangeListManagerImpl.java:671)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.c(ChangeListManagerImpl.java:546)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.access$1600(ChangeListManagerImpl.java:74)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$ActualUpdater.run(ChangeListManagerImpl.java:451)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:264)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.perforce.p4java.exception.RequestException: I/O error encountered in stream command: /var/folders/st/lgw2z0ln3cx06189g70qyx657_dzhb/T/1459525426729-0/p4j4708835924159574702.tmp (No such file or directory)
	at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execStreamCmd(NtsServerImpl.java:548)
	at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execStreamCmd(NtsServerImpl.java:434)
	at com.perforce.p4java.impl.mapbased.server.Server.execStreamCmd(Server.java:5033)
	at com.perforce.p4java.impl.mapbased.server.Server.getFileContents(Server.java:3214)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$32.run(P4Exec2.java:1038)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$32.run(P4Exec2.java:1027)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec$1.run(ClientExec.java:129)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunWithSkippedPasswordCheck(ServerRunner.java:201)
	... 29 more
Caused by: java.io.FileNotFoundException: /var/folders/st/lgw2z0ln3cx06189g70qyx657_dzhb/T/1459525426729-0/p4j4708835924159574702.tmp (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.perforce.p4java.impl.generic.core.TempFileInputStream.<init>(TempFileInputStream.java:27)
	at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execStreamCmd(NtsServerImpl.java:529)
	... 36 more
```

**Comment by gridlined** [comment]
Aside from the error encountered at the start of my day, just after opening WebStorm for the first time, I haven't had any other issues today. I also haven't restarted my WebStorm at all.

**Comment by groboclown** [comment]
Thanks for posting the log message.  That should help me out figure out the source of the issue.

**Comment by groboclown** [comment]
I added some additional error checks to work with this issue.  It should either be minimized or avoided now.

**Comment by gridlined** [comment]
When I start up WebStorm _after_ having logged into Perforce, the IDE is able to connect and perform all operations as would be expected now, from what I can tell. However, if I open Webstorm first, and then log into Perforce either via P4V or the command line ``p4 login``, it continues to say that the P4PASSWD is not set.

I have configured my P4 connection settings in Webstorm using a specific P4Config file, which contains the path to a ticket file rather than including my password in plain text. I've done this both for security purposes and because I am required to change my password every so often so the ticket file makes things easier. It may be that this particular situation is one you haven't tested against.

**Comment by groboclown** [comment]
The underlying code around login authentication has changed dramatically since this ticket was first created.  Is this still an issue?

**Comment by gridlined** [comment]
Since the ticket was opened I first switched to another Party plugin and now am completely switched over to using Git instead. I have no idea if it still is an issue in general, but it is now a non-issue for my circumstances.

**Comment by groboclown** [comment]
Thanks for getting back to me on this.  In this case, I'll keep it marked as closed.
