### ISSUE TITLE
NoSuchElementException occurs when attempting to revert files

### ISSUE THREAD

**Issue by cpozdolski** [groboclown/p4ic4idea#121]
A NoSuchElementException is thrown when attempting to revert files, both on a default and non-default changelist. 

The number of files in the changelist, as well as default vs non-default changelist type, did not seem to matter.

`null
java.util.NoSuchElementException
	at java.util.AbstractList$Itr.next(AbstractList.java:350)
	at net.groboclown.idea.p4ic.v2.server.connection.MessageResult.createForFilePath(MessageResult.java:91)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.FileActionsServerCacheSync$1.perform(FileActionsServerCacheSync.java:495)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$1.perform(ServerConnection.java:176)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$1.perform(ServerConnection.java:171)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer$1.compute(Synchronizer.java:184)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:982)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer.runImmediateAction(Synchronizer.java:172)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.runImmediately(ServerConnection.java:171)
	at net.groboclown.idea.p4ic.v2.server.P4Server$11.query(P4Server.java:594)
	at net.groboclown.idea.p4ic.v2.server.P4Server$11.query(P4Server.java:587)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.cacheQuery(ServerConnection.java:288)
	at net.groboclown.idea.p4ic.v2.server.P4Server.revertFilesOnline(P4Server.java:587)
	at net.groboclown.idea.p4ic.v2.server.P4Server.revertFiles(P4Server.java:519)
	at net.groboclown.idea.p4ic.v2.file.P4RollbackEnvironment.rollbackChanges(P4RollbackEnvironment.java:105)
	at com.intellij.openapi.vcs.changes.ui.RollbackWorker$MyRollbackRunnable$1.process(RollbackWorker.java:158)
	at com.intellij.openapi.vcs.changes.ChangesUtil.processItemsByVcs(ChangesUtil.java:376)
	at com.intellij.openapi.vcs.changes.ChangesUtil.processChangesByVcs(ChangesUtil.java:381)
	at com.intellij.openapi.vcs.changes.ui.RollbackWorker$MyRollbackRunnable.doRun(RollbackWorker.java:147)
	at com.intellij.openapi.vcs.changes.ui.RollbackWorker$MyRollbackRunnable.run(RollbackWorker.java:135)
	at com.intellij.openapi.vcs.changes.ui.RollbackWorker$3.run(RollbackWorker.java:97)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
`

**Comment by groboclown** [comment]
Thanks for the bug report.  I'm looking into it.
