### ISSUE TITLE
IDEA freezes on launch (thread deadlock)

### ISSUE THREAD

**Issue by nettlep** [groboclown/p4ic4idea#128]
Sometimes, when launching IDEA it freezes during startup. This happens after the project is loaded, the main window has appeared and there are "2 processes running...". The project tree may or may not have appeared yet. When this happens, the only option is to kill the IDEA process.

During a failed launch, VisualVM shows a deadlock is detected between two threads.

I'll include any information I think might be helpful. If you need more information, I'll be happy to oblige.

**My configuration (from the IDEA log)**

```
2016-08-31 10:47:04,637 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2016-08-31 10:47:04,658 [     21]   INFO -        #com.intellij.idea.Main - IDE: IntelliJ IDEA (build #IC-162.1628.40, 16 Aug 2016 00:00) 
2016-08-31 10:47:04,658 [     21]   INFO -        #com.intellij.idea.Main - OS: Mac OS X (10.11.6, x86_64) 
2016-08-31 10:47:04,658 [     21]   INFO -        #com.intellij.idea.Main - JRE: 1.8.0_76-release-b216 (JetBrains s.r.o) 
2016-08-31 10:47:04,659 [     22]   INFO -        #com.intellij.idea.Main - JVM: 25.76-b216 (OpenJDK 64-Bit Server VM) 
2016-08-31 10:47:04,664 [     27]   INFO -        #com.intellij.idea.Main - JVM Args: -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/Users/pn/java_error_in_idea_%p.log -XX:HeapDumpPath=/Users/pn/java_error_in_idea.hprof -Xbootclasspath/a:../lib/boot.jar -Xms128m -Xmx750m -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djb.vmOptionsFile=/Applications/IntelliJ IDEA CE.app/Contents/bin/idea.vmoptions -Didea.java.redist=jdk-bundled -Didea.home.path=/Applications/IntelliJ IDEA CE.app/Contents -Didea.executable=idea -Didea.paths.selector=IdeaIC2016.2 
2016-08-31 10:47:04,664 [     27]   INFO -        #com.intellij.idea.Main - ext: /Applications/IntelliJ IDEA CE.app/Contents/jre/jdk/Contents/Home/jre/lib/ext: [cldrdata.jar, dnsns.jar, jaccess.jar, jfxrt.jar, localedata.jar, meta-index, nashorn.jar, sunec.jar, sunjce_provider.jar, sunpkcs11.jar, zipfs.jar] 
2016-08-31 10:47:04,664 [     27]   INFO -        #com.intellij.idea.Main - ext: /System/Library/Java/Extensions: [AppleScriptEngine.jar, dns_sd.jar, j3daudio.jar, j3dcore.jar, j3dutils.jar, jai_codec.jar, jai_core.jar, libAppleScriptEngine.jnilib, libJ3D.jnilib, libJ3DAudio.jnilib, libJ3DUtils.jnilib, libmlib_jai.jnilib, mlibwrapper_jai.jar, MRJToolkit.jar, vecmath.jar] 
2016-08-31 10:47:04,664 [     27]   INFO -        #com.intellij.idea.Main - ext: /usr/lib/java: [libjdns_sd.jnilib] 
2016-08-31 10:47:04,664 [     27]   INFO -        #com.intellij.idea.Main - JNU charset: UTF-8 
2016-08-31 10:47:04,679 [     42]   INFO -        #com.intellij.idea.Main - JNA library loaded (64-bit) in 15 ms 
```

**Failed launch log (relevant portion to the end of the log)**

```
2016-08-31 10:28:28,048 [   6858]   INFO - p4ic.v2.server.P4ServerManager - No server connections known for project erector; forcing an early reload 
2016-08-31 10:28:28,052 [   6862]   INFO - ea.p4ic.config.P4ConfigProject - Loading config state 
2016-08-31 10:28:28,385 [   7195]   INFO - p4ic.v2.server.P4ServerManager - No server connections known for project erector; forcing an early reload 
2016-08-31 10:28:28,410 [   7220]   INFO - ution.rmi.RemoteProcessSupport - "/Applications/IntelliJ IDEA CE.app/Contents/jre/jdk/Contents/Home/jre/bin/java" -d64 -Djava.awt.headless=true -Didea.version==2016.2.2 -Xmx768m -Didea.maven.embedder.version=3.0.5 -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/lib/resources_en.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/log4j.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/slf4j-api-1.7.10.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/slf4j-log4j12-1.7.10.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/jna.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/jdom.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/oromatcher.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/util.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/annotations.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/snappy-in-java-0.3.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/jna-platform.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/trove4j.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/lucene-core-2.4.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven-server-api.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-common.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-lib/archetype-catalog-2.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-lib/archetype-common-2.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-lib/maven-dependency-tree-1.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-lib/nexus-indexer-3.0.4.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-lib/nexus-indexer-artifact-1.0.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven30-server-impl.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/aether-api-1.13.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/aether-connector-wagon-1.13.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/aether-impl-1.13.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/aether-spi-1.13.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/aether-util-1.13.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/commons-cli-1.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/commons-io-2.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/commons-lang-2.6.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-aether-provider-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-artifact-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-compat-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-core-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-embedder-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-model-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-model-builder-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-plugin-api-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-repository-metadata-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-settings-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-settings-builder-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/plexus-cipher-1.7.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/plexus-component-annotations-1.5.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/plexus-interpolation-1.14.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/plexus-sec-dispatcher-1.3.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/plexus-utils-2.0.6.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/sisu-guava-0.9.9.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/sisu-guice-3.1.0-no_aop.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/sisu-inject-bean-2.3.0.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/sisu-inject-plexus-2.3.0.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/wagon-file-2.8.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/wagon-http-2.8-shaded.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/wagon-http-shared-2.8.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/wagon-provider-api-2.8.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.4.jar" org.jetbrains.idea.maven.server.RemoteMavenServer 
2016-08-31 10:28:28,754 [   7564]   INFO - ution.rmi.RemoteProcessSupport - Port/ID: 46378/Maven30ServerImpl614e0667 
2016-08-31 10:28:29,339 [   8149]   INFO - p4ic.v2.server.P4ServerManager - No server connections known for project erector; forcing an early reload 
2016-08-31 10:28:29,819 [   8629]   INFO - .idea.p4ic.config.P4ConfigUtil - Found config file /Users/pn/dev/Gearbox/support/p4config, but registering it as root of file:///Users/pn/dev/Gearbox/support/bamboo-plugins/dev/erector 
2016-08-31 10:28:29,825 [   8635]   INFO - tion.ProjectConfigSourceLoader - config file mapping: {file:///Users/pn/dev/Gearbox/support={P4TRUST=null, P4CONFIG=/Users/pn/dev/Gearbox/support/p4config, P4PASSWD=<no password>, P4PORT=perforce:1666, P4TICKETS=null, P4USER=pnettle, P4CLIENT=pnettle-mbp-support, P4HOST=null}} 
2016-08-31 10:28:29,825 [   8635]   INFO - tion.ProjectConfigSourceLoader - found new builder path file:///Users/pn/dev/Gearbox/support - {P4TRUST=null, P4CONFIG=/Users/pn/dev/Gearbox/support/p4config, P4PASSWD=<no password>, P4PORT=perforce:1666, P4TICKETS=null, P4USER=pnettle, P4CLIENT=pnettle-mbp-support, P4HOST=null} 
2016-08-31 10:28:29,827 [   8637]   INFO - ea.p4ic.config.P4ConfigProject - Created config source pnettle-mbp-support:p4jrpcnts://perforce:1666 - [file:///Users/pn/dev/Gearbox/support] from {P4TRUST=null, P4CONFIG=/Users/pn/dev/Gearbox/support/p4config, P4PASSWD=<no password>, P4PORT=perforce:1666, P4TICKETS=null, P4USER=pnettle, P4CLIENT=pnettle-mbp-support, P4HOST=null}; config dirs = [file:///Users/pn/dev/Gearbox/support] 
2016-08-31 10:28:29,838 [   8648]   INFO - c.v2.extension.P4PluginVersion - Running plugin version 0.7.16 
2016-08-31 10:28:29,839 [   8649]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 3267ms; general responsiveness: ok; EDT responsiveness: 1/3 sluggish 
2016-08-31 10:28:29,849 [   8659]   INFO - p4ic.v2.server.P4ServerManager - Reconnecting to pnettle-mbp-support:p4jrpcnts://perforce:1666 
2016-08-31 10:28:29,850 [   8660]   INFO - er.connection.ServerConnection -  
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
	at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.pullNextAction(ServerConnection.java:400)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.access$1100(ServerConnection.java:50)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$QueueRunner.run(ServerConnection.java:434)
	at java.lang.Thread.run(Thread.java:745)
2016-08-31 10:28:29,851 [   8661]   INFO - p4ic.v2.server.P4ServerManager - Reconnecting to pnettle-mbp-support:p4jrpcnts://perforce:1666 
2016-08-31 10:28:29,856 [   8666]   INFO - ection.ServerConnectionManager - ** went offline: {P4TRUST=null, P4PORT=perforce:1666, P4TICKETS=null, P4USER=pnettle}
```

**Successful launch log (for reference)**
```
2016-08-31 10:47:11,548 [   6911]   INFO - p4ic.v2.server.P4ServerManager - No server connections known for project erector; forcing an early reload 
2016-08-31 10:47:11,552 [   6915]   INFO - ea.p4ic.config.P4ConfigProject - Loading config state 
2016-08-31 10:47:11,870 [   7233]   INFO - p4ic.v2.server.P4ServerManager - No server connections known for project erector; forcing an early reload 
2016-08-31 10:47:12,006 [   7369]   INFO - ution.rmi.RemoteProcessSupport - "/Applications/IntelliJ IDEA CE.app/Contents/jre/jdk/Contents/Home/jre/bin/java" -d64 -Djava.awt.headless=true -Didea.version==2016.2.2 -Xmx768m -Didea.maven.embedder.version=3.0.5 -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/lib/resources_en.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/log4j.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/slf4j-api-1.7.10.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/slf4j-log4j12-1.7.10.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/jna.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/jdom.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/oromatcher.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/util.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/annotations.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/snappy-in-java-0.3.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/jna-platform.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/trove4j.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/lucene-core-2.4.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven-server-api.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-common.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-lib/archetype-catalog-2.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-lib/archetype-common-2.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-lib/maven-dependency-tree-1.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-lib/nexus-indexer-3.0.4.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3-server-lib/nexus-indexer-artifact-1.0.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven30-server-impl.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/aether-api-1.13.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/aether-connector-wagon-1.13.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/aether-impl-1.13.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/aether-spi-1.13.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/aether-util-1.13.1.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/commons-cli-1.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/commons-io-2.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/commons-lang-2.6.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-aether-provider-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-artifact-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-compat-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-core-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-embedder-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-model-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-model-builder-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-plugin-api-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-repository-metadata-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-settings-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/maven-settings-builder-3.0.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/plexus-cipher-1.7.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/plexus-component-annotations-1.5.5.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/plexus-interpolation-1.14.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/plexus-sec-dispatcher-1.3.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/plexus-utils-2.0.6.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/sisu-guava-0.9.9.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/sisu-guice-3.1.0-no_aop.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/sisu-inject-bean-2.3.0.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/sisu-inject-plexus-2.3.0.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/wagon-file-2.8.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/wagon-http-2.8-shaded.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/wagon-http-shared-2.8.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/lib/wagon-provider-api-2.8.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.4.jar" org.jetbrains.idea.maven.server.RemoteMavenServer 
2016-08-31 10:47:12,330 [   7693]   INFO - ution.rmi.RemoteProcessSupport - Port/ID: 34624/Maven30ServerImpl481da07 
2016-08-31 10:47:12,681 [   8044]   INFO - p4ic.v2.server.P4ServerManager - No server connections known for project erector; forcing an early reload 
2016-08-31 10:47:13,168 [   8531]   INFO - .idea.p4ic.config.P4ConfigUtil - Found config file /Users/pn/dev/Gearbox/support/p4config, but registering it as root of file:///Users/pn/dev/Gearbox/support/bamboo-plugins/dev/erector 
2016-08-31 10:47:13,214 [   8577]   INFO - tion.ProjectConfigSourceLoader - config file mapping: {file:///Users/pn/dev/Gearbox/support={P4TRUST=null, P4CONFIG=/Users/pn/dev/Gearbox/support/p4config, P4PASSWD=<no password>, P4PORT=perforce:1666, P4TICKETS=null, P4USER=pnettle, P4CLIENT=pnettle-mbp-support, P4HOST=null}} 
2016-08-31 10:47:13,214 [   8577]   INFO - tion.ProjectConfigSourceLoader - found new builder path file:///Users/pn/dev/Gearbox/support - {P4TRUST=null, P4CONFIG=/Users/pn/dev/Gearbox/support/p4config, P4PASSWD=<no password>, P4PORT=perforce:1666, P4TICKETS=null, P4USER=pnettle, P4CLIENT=pnettle-mbp-support, P4HOST=null} 
2016-08-31 10:47:13,216 [   8579]   INFO - ea.p4ic.config.P4ConfigProject - Created config source pnettle-mbp-support:p4jrpcnts://perforce:1666 - [file:///Users/pn/dev/Gearbox/support] from {P4TRUST=null, P4CONFIG=/Users/pn/dev/Gearbox/support/p4config, P4PASSWD=<no password>, P4PORT=perforce:1666, P4TICKETS=null, P4USER=pnettle, P4CLIENT=pnettle-mbp-support, P4HOST=null}; config dirs = [file:///Users/pn/dev/Gearbox/support] 
2016-08-31 10:47:13,220 [   8583]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 3194ms; general responsiveness: ok; EDT responsiveness: 1/2 sluggish 
2016-08-31 10:47:13,223 [   8586]   INFO - c.v2.extension.P4PluginVersion - Running plugin version 0.7.16 
2016-08-31 10:47:13,244 [   8607]   INFO - connection.AuthenticatedServer - Opening connection 0 to p4jrpcnts://perforce:1666 with pnettle 
2016-08-31 10:47:13,244 [   8607]   INFO - connection.AuthenticatedServer - Opening connection 1 to p4jrpcnts://perforce:1666 with pnettle 
2016-08-31 10:47:13,265 [   8628]   INFO - .ui.P4MultipleConnectionWidget - updating the connection widget display 
2016-08-31 10:47:14,009 [   9372]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 6131 ms 
2016-08-31 10:47:14,242 [   9605]   INFO - .p4ic.server.ConnectionHandler - Default client hostname includes domain: [mbp.local] 
2016-08-31 10:47:14,243 [   9606]   INFO - .p4ic.server.ConnectionHandler - Default client hostname includes domain: [mbp.local] 
2016-08-31 10:47:14,540 [   9903]   INFO - e.state.ClientLocalServerState - Flushing local and server cached states for pnettle-mbp-support:p4jrpcnts://perforce:1666 
2016-08-31 10:47:14,554 [   9917]   INFO - 2.server.connection.ClientExec - Disposing ClientExec 
2016-08-31 10:47:18,009 [  13372]   INFO - 2.server.connection.ClientExec - Disposing ClientExec 
2016-08-31 10:47:18,347 [  13710]   INFO - ackerWithProcessCanceledReport - ProcessCancelException was thrown while analyzing libraries. Cache has to be rebuilt. 
2016-08-31 10:47:18,348 [  13711]   INFO - ackerWithProcessCanceledReport - ProcessCancelException was thrown while analyzing libraries. Cache has to be rebuilt. 
2016-08-31 10:47:18,348 [  13711]   INFO - ackerWithProcessCanceledReport - ProcessCancelException was thrown while analyzing libraries. Cache has to be rebuilt. 
```

**First deadlocked thread call stack**

```
"ApplicationImpl pooled thread 5" #38 prio=4 os_prio=31 tid=0x00007fb55d211000 nid=0x10c0f waiting on condition [0x00007000037d9000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007a5ff5a08> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager.setConnectionState(ServerConnectionManager.java:198)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager$3.disconnected(ServerConnectionManager.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:377)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
	at com.sun.proxy.$Proxy92.disconnected(Unknown Source)
	at net.groboclown.idea.p4ic.v2.events.Events.serverDisconnected(Events.java:109)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager$ServerConfigStatus.disconnect(ServerConnectionManager.java:252)
	at net.groboclown.idea.p4ic.v2.ui.alerts.DisconnectedHandler.<init>(DisconnectedHandler.java:33)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.checkIfOnline(ServerConnection.java:342)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.access$300(ServerConnection.java:50)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$1.run(ServerConnection.java:143)
	- locked <0x0000000793488968> (a java.lang.Object)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Second deadlocked thread call stack**

```
"ApplicationImpl pooled thread 8" #49 prio=4 os_prio=31 tid=0x00007fb559e54000 nid=0x14d0b waiting for monitor entry [0x00007000041f7000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.dispose(ServerConnection.java:162)
	- waiting to lock <0x0000000793488968> (a java.lang.Object)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager$ServerConfigStatus.dispose(ServerConnectionManager.java:299)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager.invalidateAllConfigs(ServerConnectionManager.java:188)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager$1.configUpdated(ServerConnectionManager.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:377)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:343)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
	at com.sun.proxy.$Proxy91.configUpdated(Unknown Source)
	at net.groboclown.idea.p4ic.config.P4ConfigProject.announceBaseConfigUpdated(P4ConfigProject.java:126)
	at net.groboclown.idea.p4ic.config.P4ConfigProject.initializeConfigSources(P4ConfigProject.java:266)
	at net.groboclown.idea.p4ic.config.P4ConfigProject.loadProjectConfigSources(P4ConfigProject.java:88)
	at net.groboclown.idea.p4ic.v2.server.P4ServerManager.initializeServers(P4ServerManager.java:375)
	at net.groboclown.idea.p4ic.v2.server.P4ServerManager.getServers(P4ServerManager.java:137)
	at net.groboclown.idea.p4ic.extension.P4Vcs.getP4Servers(P4Vcs.java:677)
	at net.groboclown.idea.p4ic.extension.P4Vcs.refreshServerConnectivity(P4Vcs.java:702)
	at net.groboclown.idea.p4ic.extension.P4Vcs.access$500(P4Vcs.java:75)
	at net.groboclown.idea.p4ic.extension.P4Vcs$5.run(P4Vcs.java:335)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by groboclown** [comment]
This is some great information.

It looks like an issue with a connection problem causing a loop because the IDE is in an early initialization state.  I'll need to dig into the code to get a better understanding.
