### ISSUE TITLE
Exception on IDE launch

### ISSUE THREAD

**Issue by jimkeir** [groboclown/p4ic4idea#134]
Since the latest update (0.7.18), on opening the IDE, a popup appears saying "Perforce IDEA Community Integration threw an uncaught EmptyThrowable". Happens with Android Studio 2.1 and 2.2 . I've also tried removing and reinstalling the plugin from the repository.

If I close the popup, the plugin does seem to carry on working.

Stack trace:

```
Tried to go online for a disposed connection
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:129)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager$ServerConfigStatus.setOnline(ServerConnectionManager.java:355)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager$ServerConfigStatus.onConnected(ServerConnectionManager.java:298)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec$ServerRunnerConnection.onSuccessfulCall(ClientExec.java:262)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunWithSkippedPasswordCheck(ServerRunner.java:203)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:137)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:129)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.p4RunFor(ClientExec.java:232)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.runWithServer(ClientExec.java:140)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.getServerInfo(P4Exec2.java:800)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.checkIfOnline(ServerConnection.java:365)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.access$300(ServerConnection.java:50)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$1.run(ServerConnection.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by groboclown** [comment]
I haven't tested the plugin on the latest 2.x Android Studio builds.  I'll look into this.
