### ISSUE TITLE
RelativeConfigPartPanel initialize should instead run in background

### ISSUE THREAD

**Issue by groboclown** [groboclown/p4ic4idea#139]
Noticing with big projects, the RelativeConfigPartPanel can take a long time to load.  The particular freeze happens during:

```
      at net.groboclown.idea.p4ic.config.part.RelativeConfigCompositePart.findChildP4ConfigFiles(RelativeConfigCompositePart.java:166)
      at net.groboclown.idea.p4ic.config.part.RelativeConfigCompositePart.reload(RelativeConfigCompositePart.java:78)
      at net.groboclown.idea.p4ic.config.part.RelativeConfigCompositePart.setName(RelativeConfigCompositePart.java:67)
      at net.groboclown.idea.p4ic.ui.config.props.RelativeConfigPartPanel.<init>(RelativeConfigPartPanel.java:43)
```

**Comment by groboclown** [comment]
Committed.  The problem was that a reload was happening whenever the name was set.  This seems like a really poor decision, particularly because the unmarshalling calls set name.  Now, the relative config object must be explicitly reloaded.
