### ISSUE TITLE
Cannot add file to Perforce

### ISSUE THREAD

**Issue by groboclown** [groboclown/p4ic4idea#140]
At times, the plugin will not recognize a new file as being addable.  Instead, the plugin detects the problem as an offline or can't connect error.

Here's the general log:
```
2017-02-23 09:39:35,446 [ 914137]   INFO - er.connection.ServerConnection - Running action Action AddEditAction:[Update(EDIT_FILE:[C:\test\my-file.txt]; {file=C:\test\my-file.txt, changelist=0})]
2017-02-23 09:39:35,446 [ 914137]  DEBUG - ync.FileActionsServerCacheSync - Running edit
2017-02-23 09:39:35,446 [ 914137]  DEBUG - ync.FileActionsServerCacheSync - File specs: [C:\test\my-file.txt]
2017-02-23 09:39:35,519 [ 914210]   INFO - server.connection.ServerRunner - Request problem
com.perforce.p4java.exception.RequestException: C:\test\my-file.txt - no such file(s).
        at com.perforce.p4java.impl.mapbased.server.Server.createExceptionFromMessage(Server.java:4064)
        at com.perforce.p4java.impl.mapbased.server.Server.handleFileErrorStr(Server.java:4999)
        at com.perforce.p4java.impl.mapbased.server.Server.getExtendedFiles(Server.java:3504)
        at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.getExtendedFiles(P4Exec2.java:1097)
        at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.access$200(P4Exec2.java:71)
        at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$15.run(P4Exec2.java:626)
        at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$15.run(P4Exec2.java:617)
        at net.groboclown.idea.p4ic.v2.server.connection.ClientExec$1.run(ClientExec.java:162)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunWithSkippedPasswordCheck(ServerRunner.java:228)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:149)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:141)
        at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.p4RunFor(ClientExec.java:263)
        at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.runWithClient(ClientExec.java:147)
        at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.getFileStatus(P4Exec2.java:617)
        at net.groboclown.idea.p4ic.v2.server.cache.sync.FileActionsServerCacheSync$ActionSplit.<init>(FileActionsServerCacheSync.java:891)
        at net.groboclown.idea.p4ic.v2.server.cache.sync.FileActionsServerCacheSync$AddEditAction.executeAction(FileActionsServerCacheSync.java:1176)
        at net.groboclown.idea.p4ic.v2.server.cache.sync.AbstractServerUpdateAction.perform(AbstractServerUpdateAction.java:67)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$QueueRunner$1.perform(ServerConnection.java:523)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$QueueRunner$1.perform(ServerConnection.java:498)
        at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer.runBackgroundAction(Synchronizer.java:219)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$QueueRunner.run(ServerConnection.java:498)
        at java.lang.Thread.run(Thread.java:745)
2017-02-23 09:39:35,520 [ 914211]   INFO - server.connection.ServerRunner - Some generic request problem
2017-02-23 09:39:35,520 [ 914211]   WARN - server.connection.AlertManager - Could not load the file status for these files: [C:\test\my-file.txt]
net.groboclown.idea.p4ic.server.exceptions.P4ApiException: C:\test\my-file.txt - no such file(s).
        at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunWithSkippedPasswordCheck(ServerRunner.java:343)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:149)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunFor(ServerRunner.java:141)
        at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.p4RunFor(ClientExec.java:263)
        at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.runWithClient(ClientExec.java:147)
        at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.getFileStatus(P4Exec2.java:617)
        at net.groboclown.idea.p4ic.v2.server.cache.sync.FileActionsServerCacheSync$ActionSplit.<init>(FileActionsServerCacheSync.java:891)
        at net.groboclown.idea.p4ic.v2.server.cache.sync.FileActionsServerCacheSync$AddEditAction.executeAction(FileActionsServerCacheSync.java:1176)
        at net.groboclown.idea.p4ic.v2.server.cache.sync.AbstractServerUpdateAction.perform(AbstractServerUpdateAction.java:67)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$QueueRunner$1.perform(ServerConnection.java:523)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$QueueRunner$1.perform(ServerConnection.java:498)
        at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer.runBackgroundAction(Synchronizer.java:21
9)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$QueueRunner.run(ServerConnection.java:498)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.perforce.p4java.exception.RequestException: C:\test\my-file.txt - no such file(s).
        at com.perforce.p4java.impl.mapbased.server.Server.createExceptionFromMessage(Server.java:4064)
        at com.perforce.p4java.impl.mapbased.server.Server.handleFileErrorStr(Server.java:4999)
        at com.perforce.p4java.impl.mapbased.server.Server.getExtendedFiles(Server.java:3504)
        at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.getExtendedFiles(P4Exec2.java:1097)
        at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.access$200(P4Exec2.java:71)
        at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$15.run(P4Exec2.java:626)
        at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$15.run(P4Exec2.java:617)
        at net.groboclown.idea.p4ic.v2.server.connection.ClientExec$1.run(ClientExec.java:162)
        at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunWithSkippedPasswordCheck(ServerRunner.java:228)
        ... 13 more
```

**Comment by groboclown** [comment]
Turns out an underlying API "fix" changed the error checking for authentication failures instead changed *all* errors into thrown errors.
