### ISSUE TITLE
NullPointerException soon after Android Studio starts

### ISSUE THREAD

**Issue by warwickhunter** [groboclown/p4ic4idea#150]
Plugin version: 0.9.0
Android Studio 2.3.2
Fedora Core 24
P4 server version: P4D/LINUX26X86_64/2013.1/628821 

`null
java.lang.NullPointerException
	at net.groboclown.idea.p4ic.v2.server.cache.state.P4ChangeListState.getShelvedFileStatusFor(P4ChangeListState.java:123)
	at net.groboclown.idea.p4ic.v2.server.cache.state.P4ChangeListState.addShelved(P4ChangeListState.java:118)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.ChangeListServerCacheSync.innerLoadServerCache(ChangeListServerCacheSync.java:273)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.ClientCacheManager$CacheImpl.refreshServerState(ClientCacheManager.java:393)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.WorkspaceServerCacheSync.innerLoadServerCache(WorkspaceServerCacheSync.java:494)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.CacheFrontEnd.loadServerCache(CacheFrontEnd.java:67)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.CacheFrontEnd.access$000(CacheFrontEnd.java:34)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.CacheFrontEnd$1.query(CacheFrontEnd.java:52)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.CacheFrontEnd$1.query(CacheFrontEnd.java:43)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$4.perform(ServerConnection.java:240)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer.runImmediateAction(Synchronizer.java:194)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.query(ServerConnection.java:234)
	at net.groboclown.idea.p4ic.v2.server.P4Server$4.query(P4Server.java:421)
	at net.groboclown.idea.p4ic.v2.server.P4Server$4.query(P4Server.java:415)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.cacheQuery(ServerConnection.java:346)
	at net.groboclown.idea.p4ic.v2.server.P4Server.getOpenFiles(P4Server.java:415)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider$MappedOpenFiles.<init>(P4ChangeProvider.java:361)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.getOpenedFiles(P4ChangeProvider.java:316)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.syncChanges(P4ChangeProvider.java:153)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.getChanges(P4ChangeProvider.java:143)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.actualUpdate(ChangeListManagerImpl.java:768)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.iterateScopes(ChangeListManagerImpl.java:682)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.access$1800(ChangeListManagerImpl.java:71)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$11.run(ChangeListManagerImpl.java:555)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.updateImmediately(ChangeListManagerImpl.java:552)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.access$1500(ChangeListManagerImpl.java:71)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$ActualUpdater.run(ChangeListManagerImpl.java:454)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:268)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by MalcolmEvershed** [comment]
I'm encountering a similar error.

Android Studio 2.3.2
Plugin 0.9.0
P4 Server P4D/NTX64/2017.1/1511680 (2017/05/05)

`java.lang.IllegalArgumentException: Argument for @NotNull parameter 'localPath' of net/groboclown/idea/p4ic/v2/server/cache/state/P4ShelvedFile.<init> must not be null
	at net.groboclown.idea.p4ic.v2.server.cache.state.P4ShelvedFile.<init>(P4ShelvedFile.java)
	at net.groboclown.idea.p4ic.v2.server.cache.state.P4ChangeListState.addShelved(P4ChangeListState.java:119)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.ChangeListServerCacheSync.innerLoadServerCache(ChangeListServerCacheSync.java:273)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.ClientCacheManager$CacheImpl.refreshServerState(ClientCacheManager.java:393)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.WorkspaceServerCacheSync.innerLoadServerCache(WorkspaceServerCacheSync.java:494)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.CacheFrontEnd.loadServerCache(CacheFrontEnd.java:67)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.CacheFrontEnd.access$000(CacheFrontEnd.java:34)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.CacheFrontEnd$1.query(CacheFrontEnd.java:52)
	at net.groboclown.idea.p4ic.v2.server.cache.sync.CacheFrontEnd$1.query(CacheFrontEnd.java:43)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$4.perform(ServerConnection.java:240)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer.runImmediateAction(Synchronizer.java:194)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.query(ServerConnection.java:234)
	at net.groboclown.idea.p4ic.v2.server.P4Server$4.query(P4Server.java:421)
	at net.groboclown.idea.p4ic.v2.server.P4Server$4.query(P4Server.java:415)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.cacheQuery(ServerConnection.java:346)
	at net.groboclown.idea.p4ic.v2.server.P4Server.getOpenFiles(P4Server.java:415)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider$MappedOpenFiles.<init>(P4ChangeProvider.java:461)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.getOpenedFiles(P4ChangeProvider.java:318)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.syncChanges(P4ChangeProvider.java:153)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.getChanges(P4ChangeProvider.java:143)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.actualUpdate(ChangeListManagerImpl.java:768)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.iterateScopes(ChangeListManagerImpl.java:682)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.access$1800(ChangeListManagerImpl.java:71)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$11.run(ChangeListManagerImpl.java:555)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.updateImmediately(ChangeListManagerImpl.java:552)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.access$1500(ChangeListManagerImpl.java:71)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$ActualUpdater.run(ChangeListManagerImpl.java:454)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:268)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by groboclown** [comment]
I'm looking into the issue now.

Does this prevent the plugin from being loaded?

**Comment by groboclown** [comment]
The problem stems from the Perforce server reporting no file action associated with a shelved file.  Out of curiosity, do you have shelved files in one of the changelists?  What is its status (add, delete, move, or something else)?

**Comment by MalcolmEvershed** [comment]
> Does this prevent the plugin from being loaded?

After hitting the error, clicking Refresh causes the UI to say "updating...", but it never completes. I had to uninstall and install 0.8.7 to be able to use a working version of the plugin.

> do you have shelved files in one of the changelists? What is its status (add, delete, move, or something else)?

According to `p4 changes -s shelved`, I have 4 changelists with 20 shelved files. I ran `p4 describe -s -S <changelist>` for each and all the files are either edit or add.

**Comment by MalcolmEvershed** [comment]
I looked at my Perforce server log and saw a few odd things:

    user-opened -C<my client name> <local dir path>/...
    user-fstat -m 9 <depotPath1> <depotPath2> <depotPath3> <depotPath4> (4) <depotPath9>

For some reason the log says "(4)" instead of listing the other 4 files. Though maybe this is how Perforce logs a long command.

This seems more likely to be the smoking gun as it is the last command sent by the plugin:

    user-fstat -e<changelist> -Rs //...

When I manually run `p4 fstat -e<changelist> -Rs //...`, the output is:

    //... - no such file(s).

So maybe the Perforce API or the plugin is getting tripped up by an empty changelist?

**Comment by MalcolmEvershed** [comment]
Ok, I think I may have figured it out:

Some of my shelved files have depot paths that don't map into my current client view, so the clientFile property (from p4 fstat) is not returned and neither is the isMapped property. I guess this makes sense.

**Comment by groboclown** [comment]
That does make sense.

I've made sure that the plugin only cares about shelved files in the client view.  All others are logged.

**Comment by warwickhunter** [comment]
Thanks for attacking this one so quickly.

**Comment by MalcolmEvershed** [comment]
Yeah, definitely, thanks for the fast fix and for the amazing plugin! Your plugin is so good that it's prevented me from switching from Perforce to Git. :)
