### ISSUE TITLE
IllegalStateException: did not match

### ISSUE THREAD

**Issue by groboclown** [groboclown/p4ic4idea#152]
For new files, this exception can be raised, causing the file to not be added.

```
did not match [/my/file] against []
java.lang.IllegalStateException: did not match [/my/file] against []
	at net.groboclown.idea.p4ic.v2.server.P4Server.mapExtendedFileSpecs(P4Server.java:388)
	at net.groboclown.idea.p4ic.v2.server.P4Server.getFileStatus(P4Server.java:331)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider$MappedOpenFiles.<init>(P4ChangeProvider.java:419)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.getOpenedFiles(P4ChangeProvider.java:316)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.syncChanges(P4ChangeProvider.java:153)
	at net.groboclown.idea.p4ic.v2.changes.P4ChangeProvider.getChanges(P4ChangeProvider.java:143)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.actualUpdate(ChangeListManagerImpl.java:677)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.iterateScopes(ChangeListManagerImpl.java:590)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$updateImmediately$6(ChangeListManagerImpl.java:487)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.updateImmediately(ChangeListManagerImpl.java:486)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$new$0(ChangeListManagerImpl.java:136)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:244)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by groboclown** [comment]
I haven't been able to reproduce this in the current build.
