### ISSUE TITLE
java.io.IOException: No swarm URL in configuration

### ISSUE THREAD

**Issue by warwickhunter** [groboclown/p4ic4idea#153]
Android Studio 2.3.3
Perforce Plugin 0.9.2

The plugin was working for me before I updated to 0.9.2. Now I can't get the plugin to talk 
to my Perforce instance. I get the following exception.

It seems to be complaining about the lack of a Swarm URL. How to I enter the Swarm URL in my 
project settings?

`[  28156]   WARN - swarm.SwarmConnectionComponent - Swarm server seems invalid for {P4TRUST=(no value), P4PASSWD=<no plaintext password>, P4PORT=p4proxy.oz.promptu.com:1999, P4TICKETS=(no value), P4USER=whunter, Server Fingerprint=(no value)} 
java.io.IOException: No swarm URL in configuration
        at net.groboclown.p4.simpleswarm.impl.BasicRequest.get(BasicRequest.java:59)
        at net.groboclown.p4.simpleswarm.impl.DiscoverVersion.discoverVersion(DiscoverVersion.java:34)
        at net.groboclown.p4.simpleswarm.SwarmClientFactory.createSwarmClient(SwarmClientFactory.java:26)
        at net.groboclown.idea.p4ic.swarm.SwarmConnectionComponent.refreshSwarmConfigsFor(SwarmConnectionComponent.java:97)
        at net.groboclown.idea.p4ic.swarm.SwarmConnectionComponent$1.configUpdated(SwarmConnectionComponent.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
        at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:377)
        at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
        at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:343)
        at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
        at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:226)
        at com.sun.proxy.$Proxy109.configUpdated(Unknown Source)
        at net.groboclown.idea.p4ic.config.P4ProjectConfigComponent.announceBaseConfigUpdated(P4ProjectConfigComponent.java:165)
        at net.groboclown.idea.p4ic.v2.server.P4ServerManager.initializeServers(P4ServerManager.java:427)
        at net.groboclown.idea.p4ic.v2.server.P4ServerManager.getServers(P4ServerManager.java:144)
        at net.groboclown.idea.p4ic.extension.P4Vcs.getP4Servers(P4Vcs.java:722)
        at net.groboclown.idea.p4ic.ui.P4MultipleConnectionWidget$4.run(P4MultipleConnectionWidget.java:397)
        at net.groboclown.idea.p4ic.ui.P4MultipleConnectionWidget.reloadServerRefs(P4MultipleConnectionWidget.java:407)
        at net.groboclown.idea.p4ic.ui.P4MultipleConnectionWidget.<init>(P4MultipleConnectionWidget.java:106)
        at net.groboclown.idea.p4ic.extension.P4Vcs.activate(P4Vcs.java:346)
        at com.intellij.openapi.vcs.StartedActivated$3.run(StartedActivated.java:53)
        at com.intellij.openapi.vcs.StartedActivated.callImpl(StartedActivated.java:99)
        at com.intellij.openapi.vcs.StartedActivated.doActivate(StartedActivated.java:112)
        at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings$MyVcsActivator.activate(NewMappings.java:515)
        at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.keepActiveVcs(NewMappings.java:176)
        at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.activateActiveVcses(NewMappings.java:127)
        at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings$2.run(NewMappings.java:96)
        at com.intellij.openapi.vcs.impl.VcsInitialization.execute(VcsInitialization.java:87)
        at com.intellij.openapi.vcs.impl.VcsInitialization$1$1.run(VcsInitialization.java:52)
        at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by groboclown** [comment]
Thanks for the bug report and for attaching the exception.  In this case, though, the issue with the clients isn't related to the swarm error.  I think this is related to #151 and/or #154. I'm going to close this as a duplicate.  Hopefully I can get a patch out soon.
