### ISSUE TITLE
pycharm + perforce plugin- can't read sever file error.

### ISSUE THREAD

**Issue by yr1986** [groboclown/p4ic4idea#165]
Hi All.

I'm using PyCharm with Perforce plugin.
lately i'm getting many errors of this kind:
    ERROR: problem reading server file file://<path to file>
the file that PyCharm tries to read no longer exists, it was removed from the P4 repository.
I've tried looking for a similar issue but I didn't find any solutions, can anyone help?

Attached is the idea.log file.
[idea.log](https://github.com/groboclown/p4ic4idea/files/1327705/idea.log)

**Comment by groboclown** [comment]
Sorry for the long delay in responding - I've been sidetracked from this project for a while now.

I'm confused by the log file.  The reported stack trace location:

```
Caused by: java.lang.NullPointerException
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$32.run(P4Exec2.java:1047)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$32.run(P4Exec2.java:1027)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec$1.run(ClientExec.java:129)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerRunner.p4RunWithSkippedPasswordCheck(ServerRunner.java:213)
```

looks like it came from a very old version of the plugin (July 2017 would be when the code first looked like that, and it was later changed to a different line number in August 4, 2017, which was part of the 0.9.5 release).  Could you update the plugin and see if the same issue is still happening?

**Comment by groboclown** [comment]
Closing off issue due to inactivity.
