### ISSUE TITLE
Plugin 'PerforceIC' failed to initialize and will be disabled. Please restart Pycharm.

### ISSUE THREAD

**Issue by varundey** [groboclown/p4ic4idea#168]
Enabling the plugin and restarting Pycharm causes the it to crash and restart with plugin disabled in MacOS 10.12.6.
 <img width="885" alt="screen shot 2018-03-02 at 2 11 31 pm" src="https://user-images.githubusercontent.com/9202135/36890413-be3ee27c-1e23-11e8-8c22-74414c26cd7e.png">

Steps to reproduce
1. Enable the plugin by going to PyCharm Preferences -> Plugins -> Perforce IDEA Community Integration
2. Click on Apply and hit OK
3. Pycharm will ask you to restart
4. Upon restarting, it'll throw up the exception shown above

Full log: 
`java.lang.ExceptionInInitializerError
    at net.groboclown.idea.p4ic.v2.server.cache.state.P4ChangeListState.<clinit>(P4ChangeListState.java:45)
    at net.groboclown.idea.p4ic.v2.server.cache.state.P4ClientState.deserialize(P4ClientState.java:225)
    at net.groboclown.idea.p4ic.v2.server.cache.state.ClientLocalServerState.deserialize(ClientLocalServerState.java:169)
    at net.groboclown.idea.p4ic.v2.server.cache.state.AllClientsState.loadState(AllClientsState.java:160)
    at net.groboclown.idea.p4ic.v2.server.cache.state.AllClientsState.loadState(AllClientsState.java:49)
    at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:328)
    at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:290)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:495)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:181)
    at net.groboclown.idea.p4ic.v2.server.cache.state.AllClientsState.getInstance(AllClientsState.java:64)
    at net.groboclown.idea.p4ic.v2.server.cache.CentralCacheManager.<init>(CentralCacheManager.java:50)
    at net.groboclown.idea.p4ic.v2.server.connection.ServerConnectionManager.<init>(ServerConnectionManager.java:77)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:474)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:454)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:65)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: Color parameter outside of expected range: Green
    at java.awt.Color.testColorValueRange(Color.java:310)
    at java.awt.Color.<init>(Color.java:395)
    at java.awt.Color.<init>(Color.java:369)
    at net.groboclown.idea.p4ic.extension.P4Vcs.toShelvedColor(P4Vcs.java:790)
    at net.groboclown.idea.p4ic.extension.P4Vcs.<clinit>(P4Vcs.java:121)
    ... 55 more
`

**Comment by groboclown** [comment]
Thanks for the bug report.  It looks like you ran into a bug related to getting the text color for shelved changes.  Fortunately, this bug is easy to fix.

**Comment by varundey** [comment]
Is the fix for this going to come in next release?

**Comment by groboclown** [comment]
This should be available in the 0.9.6 release.

https://plugins.jetbrains.com/plugin/7685-perforce-idea-community-integration/update/43812

Does this not work for you?

**Comment by varundey** [comment]
Hm strange! I did not get any notif for the update.

**Comment by varundey** [comment]
Okay refreshed the plugins and updated. Working again like a charm. Thanks for this :)
