### ISSUE TITLE
Unable to use plugin with Guidewire Studio 1.1.15

### ISSUE THREAD

**Issue by rickhoang** [groboclown/p4ic4idea#171]
I'm using Guidewire Studio with Guidewire Claim Center 9. The studio is based on the IntelliJ Community Edition. I can't seem to add the Perforce Integration Plugin. Below is the stacktrace.

2018-07-18 12:25:59,134 [ 370115]  ERROR - .impl.projectlevelman.AllVcses - Guidewire Studio 1.1.15  Build #Studio-1.0 
2018-07-18 12:25:59,134 [ 370115]  ERROR - .impl.projectlevelman.AllVcses - JDK: 1.8.0_152 
2018-07-18 12:25:59,134 [ 370115]  ERROR - .impl.projectlevelman.AllVcses - VM: Dynamic Code Evolution 64-Bit Server VM 
2018-07-18 12:25:59,134 [ 370115]  ERROR - .impl.projectlevelman.AllVcses - Vendor: Oracle Corporation 
2018-07-18 12:25:59,134 [ 370115]  ERROR - .impl.projectlevelman.AllVcses - OS: Windows 7 
2018-07-18 12:25:59,134 [ 370115]  ERROR - .impl.projectlevelman.AllVcses - Last Action: ShowLog 
2018-07-18 12:25:59,134 [ 370115]  ERROR - penapi.actionSystem.impl.Utils - update failed for AnAction with ID=Vcs.ShowTabbedFileHistory 
java.lang.NullPointerException
	at com.intellij.openapi.vcs.impl.projectlevelman.AllVcses.registerVcs(AllVcses.java:64)
	at com.intellij.openapi.vcs.impl.projectlevelman.AllVcses.addVcs(AllVcses.java:58)
	at com.intellij.openapi.vcs.impl.projectlevelman.AllVcses.getByName(AllVcses.java:108)
	at com.intellij.openapi.vcs.impl.ProjectLevelVcsManagerImpl.getVcsFor(ProjectLevelVcsManagerImpl.java:287)
	at com.intellij.openapi.vcs.actions.TabbedShowHistoryAction.isEnabled(TabbedShowHistoryAction.java:54)
	at com.intellij.openapi.vcs.actions.TabbedShowHistoryAction.update(TabbedShowHistoryAction.java:35)
	at com.intellij.openapi.vcs.actions.AbstractVcsAction$1.run(AbstractVcsAction.java:58)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:946)
	at com.intellij.openapi.vcs.actions.AbstractVcsAction.performUpdate(AbstractVcsAction.java:55)
	at com.intellij.openapi.vcs.actions.AbstractVcsAction.performUpdate(AbstractVcsAction.java:33)
	at com.intellij.openapi.actionSystem.AsyncUpdateAction.update(AsyncUpdateAction.java:65)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:114)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:96)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:937)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:64)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:173)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:191)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushRequest(FocusManagerImpl.java:675)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushNow(FocusManagerImpl.java:656)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushIdleRequests(FocusManagerImpl.java:626)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$11.run(FocusManagerImpl.java:522)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2361)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:500)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:108)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.access$400(ToolbarUpdater.java:40)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyTimerListener.run(ToolbarUpdater.java:163)
	at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:50)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.runListenerAction(ActionManagerImpl.java:1489)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.notifyListeners(ActionManagerImpl.java:1479)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1463)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-07-18 12:25:59,144 [ 370125]  ERROR - penapi.actionSystem.impl.Utils - Guidewire Studio 1.1.15  Build #Studio-1.0 
2018-07-18 12:25:59,144 [ 370125]  ERROR - penapi.actionSystem.impl.Utils - JDK: 1.8.0_152 
2018-07-18 12:25:59,144 [ 370125]  ERROR - penapi.actionSystem.impl.Utils - VM: Dynamic Code Evolution 64-Bit Server VM 
2018-07-18 12:25:59,144 [ 370125]  ERROR - penapi.actionSystem.impl.Utils - Vendor: Oracle Corporation 
2018-07-18 12:25:59,144 [ 370125]  ERROR - penapi.actionSystem.impl.Utils - OS: Windows 7 
2018-07-18 12:25:59,144 [ 370125]  ERROR - penapi.actionSystem.impl.Utils - Last Action: ShowLog

**Comment by groboclown** [comment]
The issue you're reporting comes from the IDE running into a problem while loading the plugin.  Unfortunately, I cannot find any information on which underlying JetBrains IDE version the Guidewire Studio product uses, and the website documentation does not give me information about it, either.  This will be critical to helping me understand where to find the root cause.

Do you happen to know which version it's based off?

**Comment by rickhoang** [comment]
Found it. It's 15.0.6

**Comment by rickhoang** [comment]
Okay, this is the latest log that I have after using your latest plugin. 

2018-08-01 12:47:40,354 [  65535]   INFO - org.jetbrains.io.BuiltInServer - web server stopped 
2018-08-01 12:47:40,354 [  65535]   INFO - Types.impl.FileTypeManagerImpl - FileTypeManager: 0 auto-detected files
Elapsed time on auto-detect: 0 ms 
2018-08-01 12:47:40,385 [  65566]   INFO - il.indexing.FileBasedIndexImpl - START INDEX SHUTDOWN 
2018-08-01 12:47:40,432 [  65613]   INFO - il.indexing.FileBasedIndexImpl - END INDEX SHUTDOWN 
2018-08-01 12:47:40,432 [  65613]   INFO - stubs.SerializationManagerImpl - START StubSerializationManager SHUTDOWN 
2018-08-01 12:47:40,432 [  65613]   INFO - stubs.SerializationManagerImpl - END StubSerializationManager SHUTDOWN 
2018-08-01 12:47:40,510 [  65691]   WARN - pl.local.NativeFileWatcherImpl - Watcher terminated with exit code 0 
2018-08-01 12:47:40,510 [  65691]   INFO - newvfs.persistent.PersistentFS - VFS dispose started 
2018-08-01 12:47:40,588 [  65769]   INFO - newvfs.persistent.PersistentFS - VFS dispose completed 
2018-08-01 12:47:41,212 [  66393]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------ 
2018-08-01 12:47:41,212 [  66393]   INFO - org.jetbrains.io.BuiltInServer - web server stopped 
2018-08-01 12:47:46,079 [   1061]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2018-08-01 12:47:46,157 [   1139]   INFO -        #com.intellij.idea.Main - IDE: IntelliJ IDEA (build #IC-143.2370.31, 28 Apr 2016 00:00) 
2018-08-01 12:47:46,157 [   1139]   INFO -        #com.intellij.idea.Main - OS: Windows 7 (6.1, amd64) 
2018-08-01 12:47:46,157 [   1139]   INFO -        #com.intellij.idea.Main - JRE: 1.8.0_152-b16 (Oracle Corporation) 
2018-08-01 12:47:46,157 [   1139]   INFO -        #com.intellij.idea.Main - JVM: 25.71-b01-dcevmlight-30 (Dynamic Code Evolution 64-Bit Server VM) 
2018-08-01 12:47:46,157 [   1139]   INFO -        #com.intellij.idea.Main - JVM Args: -Xbootclasspath/a:../lib/boot.jar -XX:ReservedCodeCacheSize=64m -ea -Didea.properties.file=C:/DEV/GW9S/ClaimCenter/.idea/settings/idea.properties -Dstudio.sdkroot=C:/DEV/GW9S/ClaimCenter -Didea.plugins.compatible.build=143.2370.31 -Dstudio.minimum.preferred.idea.version=143.2370 -Dfile.encoding=UTF-8 -Dide.tooltip.dismissDelay=60000 -Dapple.laf.useScreenMenuBar=true -Dapple.awt.application.name=Guidewire Studio -Djdk.util.zip.ensureTrailingSlash=false -Xmx4g 
2018-08-01 12:47:46,157 [   1139]   INFO -        #com.intellij.idea.Main - ext: C:\Program Files\Java\jdk1.8.0_152\jre\lib\ext: [access-bridge-64.jar, cldrdata.jar, dnsns.jar, jaccess.jar, jfxrt.jar, localedata.jar, meta-index, nashorn.jar, sunec.jar, sunjce_provider.jar, sunmscapi.jar, sunpkcs11.jar, zipfs.jar] 
2018-08-01 12:47:46,235 [   1217]   INFO -        #com.intellij.idea.Main - JNA library loaded (64-bit) in 78 ms 
2018-08-01 12:47:46,235 [   1217]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational 
2018-08-01 12:47:46,251 [   1233]   INFO -        #com.intellij.idea.Main - Using "FocusKiller" library to prevent focus stealing. 
2018-08-01 12:47:47,935 [   2917]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor duplicates-groovy.xml 
2018-08-01 12:47:48,762 [   3744]   INFO - llij.ide.plugins.PluginManager - 37 plugins initialized in 1419 ms 
2018-08-01 12:47:48,793 [   3775]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: Git Integration (8.1), GitHub (143.2370.31), Gradle (143.2370.31), Groovy (9.0), I18n for Java (143.2370.31), IDEA CORE (143.SNAPSHOT), JUnit (1.0), Properties Support (143.SNAPSHOT), Terminal (0.1) 
2018-08-01 12:47:48,793 [   3775]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Gosu (1.1.15-rc-SNAPSHOT), Gosu Inspections Plugin (1.1.15-rc-SNAPSHOT), Guidewire Merge Tracker (1.32.0), Guidewire Services Best Practices (1.1.15-rc-SNAPSHOT), Guidewire Studio (1.1.15-rc-SNAPSHOT), Guidewire Upgrade Inspections (Ferrite) (1.32.0), Perforce IDEA Community Integration (0.9.6) 
2018-08-01 12:47:48,793 [   3775]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: Android Support (10.1.3.0), Ant Support (1.0), Bytecode Viewer (0.1), CVS Integration (11), Copyright (8.1), Coverage (143.SNAPSHOT), Eclipse Integration (3.0), EditorConfig (1.0), IntelliLang (8.0), JavaFX (1.0), Kotlin (1.0.1-release-IJ143-40), Maven Integration (143.2370.31), Plugin DevKit (1.0), Settings Repository (143.2370.31), Subversion Integration (1.1), Task Management (1.0), TestNG-J (8.0), UI Designer (143.2370.31), XPathView + XSLT Support (4), XSLT-Debugger (1.4), hg4idea (10.0) 
2018-08-01 12:47:49,589 [   4571]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=4130865152 
2018-08-01 12:47:49,714 [   4696]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: C:\DEV\GW9S\ClaimCenter\studio\sdk\bin\fsnotifier64.exe 
2018-08-01 12:47:49,776 [   4758]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2018-08-01 12:47:51,258 [   6240]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2018-08-01 12:47:53,177 [   8159]   INFO - plication.impl.ApplicationImpl - 86 application components initialized in 5834 ms 
2018-08-01 12:47:53,208 [   8190]   INFO - .intellij.idea.IdeaApplication - App initialization took 9262 ms 
2018-08-01 12:47:53,395 [   8377]   INFO - ateSettings.impl.UpdateChecker - Connection failed (Unrecognized SSL message, plaintext connection?). Please check network connection and try again. 
2018-08-01 12:47:56,047 [  11029]   INFO - CompilerWorkspaceConfiguration - Available processors: 8 
2018-08-01 12:47:56,422 [  11404]   INFO - ellij.project.impl.ProjectImpl - 132 project components initialized in 2153 ms 
2018-08-01 12:47:56,609 [  11591]   INFO - le.impl.ModuleManagerComponent - 1 module(s) loaded in 187 ms 
2018-08-01 12:47:58,325 [  13307]   INFO - .studio.init.StudioEnvironment - Minimum preferred build of IDEA is 143.2370 
2018-08-01 12:47:58,325 [  13307]   INFO - .studio.init.StudioEnvironment - Most recently tested IDEA build is 143.2370.31 
2018-08-01 12:47:58,325 [  13307]   INFO - .studio.init.StudioEnvironment - Currently running IDEA build 143.2370 
2018-08-01 12:47:58,466 [  13448]   WARN -                  STUDIO.UPDATE - Failed to check for Studio update. Unrecognized SSL message, plaintext connection? 
2018-08-01 12:48:02,537 [  17519]   INFO - tartup.impl.StartupManagerImpl - C:/DEV/GW9S/ClaimCenter/.idea/misc.xml case-sensitivity: false 
2018-08-01 12:48:02,553 [  17535]   INFO - onfig.P4ProjectConfigComponent - VCS directory mappings changed; marking P4 configs as needing refresh. 
2018-08-01 12:48:04,269 [  19251]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 10111 ms 
2018-08-01 12:48:05,018 [  20000]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 843ms; general responsiveness: ok; EDT responsiveness: ok 
2018-08-01 12:48:06,562 [  21544]   INFO - 4ic.compat.CompatFactoryLoader - Using compatibility features CompatFactory150 
2018-08-01 12:48:09,058 [  24040]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 4040ms; general responsiveness: 1/4 sluggish; EDT responsiveness: 0/4 sluggish, 1/4 very slow 
2018-08-01 12:48:10,930 [  25912]   INFO - p4ic.v2.server.P4ServerManager - source load has errors: [problem(MultipleDataPart(file://C:/DEV/GW9S/ClaimCenter):1: configuration.problem.username -> Missing username definition.), problem(MultipleDataPart(file://C:/DEV/GW9S/ClaimCenter):1: error.config.no-client -> No client name in configuration)] 
2018-08-01 12:48:11,772 [  26754]   INFO - dvertisement.PluginsAdvertiser - Unrecognized SSL message, plaintext connection? 
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:284)
	at com.intellij.util.io.HttpRequests.access$000(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$1RequestImpl.getConnection(HttpRequests.java:139)
	at com.intellij.ide.plugins.RepositoryHelper$2.process(RepositoryHelper.java:220)
	at com.intellij.ide.plugins.RepositoryHelper$2.process(RepositoryHelper.java:213)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:232)
	at com.intellij.util.io.RequestBuilder.connect(RequestBuilder.java:128)
	at com.intellij.ide.plugins.RepositoryHelper.loadPlugins(RepositoryHelper.java:213)
	at com.intellij.ide.plugins.RepositoryHelper.loadPlugins(RepositoryHelper.java:124)
	at com.intellij.ide.plugins.RepositoryHelper.loadPlugins(RepositoryHelper.java:105)
	at com.intellij.ide.plugins.RepositoryHelper.loadPluginsFromAllRepositories(RepositoryHelper.java:84)
	at com.intellij.openapi.updateSettings.impl.pluginsAdvertisement.PluginsAdvertiser$5$1.run(PluginsAdvertiser.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by groboclown** [comment]
I see the line "IntelliJ IDEA (build #IC-143.2370.31, 28 Apr 2016 00:00)", which, according to [the build range number list](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html), makes this based on IntelliJ IDEA 15.

That version of IntelliJ will work only with the older version of the plugin (the 0.9 line), which is going on limited support right now.  I'm focusing on releasing the new version (currently 0.10), which only supports versions 17+.

That said, the log you provided shows the plugin loading, but failing to connect to the server due to the error:

```
p4ic.v2.server.P4ServerManager - source load has errors: [problem(MultipleDataPart(file://C:/DEV/GW9S/ClaimCenter):1: configuration.problem.username -> Missing username definition.), problem(MultipleDataPart(file://C:/DEV/GW9S/ClaimCenter):1: error.config.no-client -> No client name in configuration)]
```

**Comment by groboclown** [comment]
The 0.9 release line is dormant, and it looks like the Guidewire IDE is running a version of the community edition platform earlier than 17.1.  I'd like to hear if the 0.10 release of the plugin works with this IDE.
