### ISSUE TITLE
"AWT events are not allowed inside write action" error after VCS->Checkout from Version Control

### ISSUE THREAD

**Issue by Slach** [groboclown/p4ic4idea#196]
**Describe the bug**
PyCharm 2018.3.5 (Community Edition)
Build #PC-183.5912.18, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**To Reproduce**
- open Menu VCS->Enable version Control
- choose Perforce
- open Menu VCS->Checkout from Version Control->Perforce
- Press Check connection
- Press OK
- Open Folder which was checkouted in current window

**Expected behavior**
In "version control" bottom tab see one new active connection
** Current behavior**
```
java.lang.Throwable: There is no request for kite.obsfucated.hh@551bb101
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:593)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at com.intellij.ide.IdeEventQueue.flushQueue(IdeEventQueue.java:742)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:185)
	at com.intellij.openapi.vcs.checkout.ProjectDirCheckoutListener.processCheckedOutDirectory(ProjectDirCheckoutListener.java:31)
	at com.intellij.openapi.vcs.checkout.CompositeCheckoutListener.notifyCheckoutListeners(CompositeCheckoutListener.java:48)
	at com.intellij.openapi.vcs.checkout.CompositeCheckoutListener.directoryCheckedOut(CompositeCheckoutListener.java:39)
	at net.groboclown.p4plugin.extension.P4CheckoutProvider$1.onSuccess(P4CheckoutProvider.java:123)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:502)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:421)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by groboclown** [comment]
Thanks for the stack trace.  That's helping me pinpoint this issue.

**Comment by groboclown** [comment]
I *think* I have a fix for this.  It will be in the next release.

**Comment by jzyhywxz** [comment]
@groboclown How do you fix the bug? May I know your solution? Thanks.

**Comment by groboclown** [comment]
The affected code is here:

https://github.com/groboclown/p4ic4idea/commit/5539d120901481ba768fd6af8d11ed659df33a23#diff-a286f9b9cac250017d057d0836a270e9

If you search for the bug # in the comments (#196).

The fix was to run the `listener.directoryCheckedOut` code in a separate thread.  A more efficient implementation should perform a check to see if the current thread is the EDT, and only then run the code in a separate thread, but this isn't code that's expected to be highly performant.

**Comment by jzyhywxz** [comment]
@groboclown Thank you very much! It works!
