### ISSUE TITLE
Using Zulu 1.8 JDK causes Internal Error

### ISSUE THREAD

**Issue by aaron-mar** [groboclown/p4ic4idea#207]
**Describe the bug**
Using Zulu 1.8 JDK and set the JAVA_HOME to point to this JDK causes this error:

8:03 AM	P4 Plugin Error: Internal error: null

It seems it cannot connect to perforce to get the list of open files for each changelist.

The version of Zulu JDK:

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (Zulu 8.42.0.14-SA-win64) (build 1.8.0_232-b18)
OpenJDK 64-Bit Server VM (Zulu 8.42.0.14-SA-win64) (build 25.232-b18, mixed mode)

When I convert back to another JDK, things start to work again.

**To Reproduce**
1. Install the perforce plugin (v0.10.10)
2. Set up perforce to connect to a valid server
3. Test the connection

**Expected behavior**
The test connection should connect and end cleanly.

**Attachments**
Here is a log of the problem:
2020-01-28 08:03:02,821 [   6956]  ERROR - r.PlatformComponentManagerImpl - IntelliJ IDEA 2019.3.2  Build #IC-193.6015.39 
2020-01-28 08:03:02,821 [   6956]  ERROR - r.PlatformComponentManagerImpl - JDK: 11.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-01-28 08:03:02,822 [   6957]  ERROR - r.PlatformComponentManagerImpl - OS: Windows 10 
2020-01-28 08:03:02,822 [   6957]  ERROR - r.PlatformComponentManagerImpl - Plugin to blame: JavaDoc version: 3.1.0 
2020-01-28 08:03:02,822 [   6957]  ERROR - r.PlatformComponentManagerImpl - Last Action:  
2020-01-28 08:03:03,378 [   7513]   INFO - anguage.common.SimpleTokenType - Registering element DATA_TYPE for language ORACLE-SQL (37) 
2020-01-28 08:03:03,378 [   7513]   INFO - anguage.common.SimpleTokenType - Registering element KEYWORD for language ORACLE-SQL (38) 
2020-01-28 08:03:03,378 [   7513]   INFO - anguage.common.SimpleTokenType - Registering element FUNCTION for language ORACLE-SQL (39) 
2020-01-28 08:03:03,378 [   7513]   INFO - anguage.common.SimpleTokenType - Registering element PARAMETER for language ORACLE-SQL (40) 
2020-01-28 08:03:03,378 [   7513]   INFO - anguage.common.SimpleTokenType - Registering element EXCEPTION for language ORACLE-SQL (41) 
2020-01-28 08:03:03,807 [   7942]   INFO - pl$FileIndexDataInitialization - Initialization done: 6598 
2020-01-28 08:03:04,023 [   8158]   INFO - exImpl$StubIndexInitialization - Initialization done: 215 
2020-01-28 08:03:04,773 [   8908]   INFO - .diagnostic.PerformanceWatcher - Post-startup activities under progress took 3744ms; general responsiveness: ok; EDT responsiveness: 1/4 sluggish 
2020-01-28 08:03:04,953 [   9088]   INFO - tartup.impl.StartupManagerImpl - D:/dev/projects/intellij/devfuture/.idea case-sensitivity: expected=false actual=false 
2020-01-28 08:03:04,986 [   9121]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 1179ms; general responsiveness: ok; EDT responsiveness: 1/1 sluggish 
2020-01-28 08:03:05,639 [   9774]   INFO -                             p4 - cmd (1): p4 info 
2020-01-28 08:03:05,639 [   9774]   INFO -                             p4 - cmd (1): p4 info 
2020-01-28 08:03:05,668 [   9803]   INFO -                             p4 - cmd (2): p4 client -o client_repo 
2020-01-28 08:03:05,668 [   9803]   INFO -                             p4 - cmd (2): p4 client -o client_repo
2020-01-28 08:03:05,697 [   9832]   INFO - onnection.ConnectCommandRunner - Starting listOpenedFilesChanges at Tue Jan 28 08:03:05 PST 2020 
2020-01-28 08:03:05,723 [   9858]   INFO -                             p4 - cmd (3): p4 changes -i -cclient_repo -m500 -spending -uuser
2020-01-28 08:03:05,723 [   9858]   INFO -                             p4 - cmd (3): p4 fstat -m1 D:/dev/client_repo/...#have 
2020-01-28 08:03:05,730 [   9865]   INFO -                             p4 - cmd (4): p4 change -s -o 435764 
2020-01-28 08:03:05,790 [   9925]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 7707 ms 
2020-01-28 08:03:05,794 [   9929]   INFO -                             p4 - cmd (5): p4 describe -s 435764 
2020-01-28 08:03:05,796 [   9931]   INFO -                             p4 - cmd (6): p4 change -s -o 435132 
2020-01-28 08:03:05,857 [   9992]   INFO -                             p4 - cmd (7): p4 describe -s 435132 
2020-01-28 08:03:05,862 [   9997]   INFO -                             p4 - cmd (8): p4 change -s -o 435077 
2020-01-28 08:03:05,922 [  10057]   INFO -                             p4 - cmd (9): p4 describe -s 435077 
2020-01-28 08:03:05,924 [  10059]   INFO -                             p4 - cmd (10): p4 change -s -o 435066 
2020-01-28 08:03:05,983 [  10118]   INFO -                             p4 - cmd (11): p4 describe -s 435066 
2020-01-28 08:03:05,985 [  10120]   INFO -                             p4 - cmd (12): p4 change -s -o 432984 
2020-01-28 08:03:06,044 [  10179]   INFO -                             p4 - cmd (13): p4 describe -s 432984 
2020-01-28 08:03:06,046 [  10181]   INFO -                             p4 - cmd (14): p4 change -s -o 428775 
2020-01-28 08:03:06,105 [  10240]   INFO -                             p4 - cmd (15): p4 describe -s 428775 
2020-01-28 08:03:06,107 [  10242]   INFO -                             p4 - cmd (16): p4 change -s -o 428315 
2020-01-28 08:03:06,166 [  10301]   INFO -                             p4 - cmd (17): p4 describe -s 428315 
2020-01-28 08:03:06,168 [  10303]   INFO -                             p4 - cmd (18): p4 change -s -o 425434 
2020-01-28 08:03:06,229 [  10364]   INFO -                             p4 - cmd (19): p4 describe -s 425434 
2020-01-28 08:03:06,234 [  10369]   INFO -                             p4 - cmd (20): p4 fstat -m5000 -edefault -Rc -Ro -Ol -Op -Oh //client_repo/... 
2020-01-28 08:03:06,242 [  10377]   INFO -                             p4 - cmd (21): p4 where //depot/projects/.... 
2020-01-28 08:03:06,245 [  10380]   INFO - onnection.ConnectCommandRunner - Finished listOpenedFilesChanges; started at Tue Jan 28 08:03:05 PST 2020, ended at Tue Jan 28 08:03:06 PST 2020 
2020-01-28 08:03:06,246 [  10381]   WARN - nnection.P4RequestErrorHandler - Running an action with the Perforce server client:server_host:1666@client_repo generated an error. 
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.listOpenedFilesChanges(ConnectCommandRunner.java:1021)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$listOpenedFilesChanges$29(ConnectCommandRunner.java:336)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$0(SimpleConnectionManager.java:123)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:156)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:54)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$5(SimpleConnectionManager.java:571)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:589)
	at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-01-28 08:03:06,251 [  10386]   WARN - .components.UserErrorComponent -  
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.listOpenedFilesChanges(ConnectCommandRunner.java:1021)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$listOpenedFilesChanges$29(ConnectCommandRunner.java:336)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$0(SimpleConnectionManager.java:123)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:156)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:54)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$5(SimpleConnectionManager.java:571)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:589)
	at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-01-28 08:03:06,253 [  10388]   INFO - n.impl.SimpleConnectionManager - Command execution failed 
net.groboclown.p4.server.api.P4CommandRunner$ServerResultException: Unknown error
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.createServerResultException(P4RequestErrorHandler.java:131)
	at net.groboclown.p4.server.impl.connection.impl.MessageP4RequestErrorHandler.handleException(MessageP4RequestErrorHandler.java:512)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:161)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:54)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$5(SimpleConnectionManager.java:571)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:589)
	at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.listOpenedFilesChanges(ConnectCommandRunner.java:1021)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$listOpenedFilesChanges$29(ConnectCommandRunner.java:336)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$0(SimpleConnectionManager.java:123)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:156)
	... 10 more
2020-01-28 08:03:06,256 [  10391]   INFO - gin.extension.P4ChangeProvider - Processing changes in file://D:/dev/devfuture 
2020-01-28 08:03:07,428 [  11563]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 2437ms; general responsiveness: ok; EDT responsiveness: 1/3 sluggish 
2020-01-28 08:03:10,725 [  14860]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 1/28/2020 7:19 AM) 
2020-01-28 08:03:10,942 [  15077]   INFO - ge.ExternalProjectsDataStorage - Load external projects data in 2 millis (read time: 2) 
2020-01-28 08:03:15,929 [  20064]   INFO -                             p4 - cmd (1): p4 info 
2020-01-28 08:03:15,931 [  20066]   INFO -                             p4 - cmd (2): p4 client -o client_repo 
2020-01-28 08:03:15,940 [  20075]   INFO - onnection.ConnectCommandRunner - Starting listOpenedFilesChanges at Tue Jan 28 08:03:15 PST 2020 
2020-01-28 08:03:15,946 [  20081]   INFO -                             p4 - cmd (3): p4 changes -i -cclient_repo -m500 -spending -uuser 
2020-01-28 08:03:15,950 [  20085]   INFO -                             p4 - cmd (4): p4 change -s -o 435764 
2020-01-28 08:03:16,008 [  20143]   INFO -                             p4 - cmd (5): p4 describe -s 435764 
2020-01-28 08:03:16,010 [  20145]   INFO -                             p4 - cmd (6): p4 change -s -o 435132 
2020-01-28 08:03:16,069 [  20204]   INFO -                             p4 - cmd (7): p4 describe -s 435132 
2020-01-28 08:03:16,071 [  20206]   INFO -                             p4 - cmd (8): p4 change -s -o 435077 
2020-01-28 08:03:16,131 [  20266]   INFO -                             p4 - cmd (9): p4 describe -s 435077 
2020-01-28 08:03:16,133 [  20268]   INFO -                             p4 - cmd (10): p4 change -s -o 435066 
2020-01-28 08:03:16,191 [  20326]   INFO -                             p4 - cmd (11): p4 describe -s 435066 
2020-01-28 08:03:16,193 [  20328]   INFO -                             p4 - cmd (12): p4 change -s -o 432984 
2020-01-28 08:03:16,251 [  20386]   INFO -                             p4 - cmd (13): p4 describe -s 432984 
2020-01-28 08:03:16,253 [  20388]   INFO -                             p4 - cmd (14): p4 change -s -o 428775 
2020-01-28 08:03:16,311 [  20446]   INFO -                             p4 - cmd (15): p4 describe -s 428775 
2020-01-28 08:03:16,313 [  20448]   INFO -                             p4 - cmd (16): p4 change -s -o 428315 
2020-01-28 08:03:16,371 [  20506]   INFO -                             p4 - cmd (17): p4 describe -s 428315 
2020-01-28 08:03:16,373 [  20508]   INFO -                             p4 - cmd (18): p4 change -s -o 425434 
2020-01-28 08:03:16,431 [  20566]   INFO -                             p4 - cmd (19): p4 describe -s 425434 
2020-01-28 08:03:16,432 [  20567]   INFO -                             p4 - cmd (20): p4 fstat -m5000 -edefault -Rc -Ro -Ol -Op -Oh //client_repo/... 
2020-01-28 08:03:16,436 [  20571]   INFO -                             p4 - cmd (21): p4 where //depot/projects/...... 
2020-01-28 08:03:16,438 [  20573]   INFO - onnection.ConnectCommandRunner - Finished listOpenedFilesChanges; started at Tue Jan 28 08:03:15 PST 2020, ended at Tue Jan 28 08:03:16 PST 2020 
2020-01-28 08:03:16,438 [  20573]   WARN - nnection.P4RequestErrorHandler - Running an action with the Perforce server client:server_host:1666@client_repo generated an error. 
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.listOpenedFilesChanges(ConnectCommandRunner.java:1021)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$listOpenedFilesChanges$29(ConnectCommandRunner.java:336)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$0(SimpleConnectionManager.java:123)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:156)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:54)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$5(SimpleConnectionManager.java:571)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:589)
	at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-01-28 08:03:16,439 [  20574]   WARN - .components.UserErrorComponent -  
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.listOpenedFilesChanges(ConnectCommandRunner.java:1021)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$listOpenedFilesChanges$29(ConnectCommandRunner.java:336)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$0(SimpleConnectionManager.java:123)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:156)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:54)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$5(SimpleConnectionManager.java:571)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:589)
	at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-01-28 08:03:16,439 [  20574]   INFO - n.impl.SimpleConnectionManager - Command execution failed 
net.groboclown.p4.server.api.P4CommandRunner$ServerResultException: Unknown error
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.createServerResultException(P4RequestErrorHandler.java:131)
	at net.groboclown.p4.server.impl.connection.impl.MessageP4RequestErrorHandler.handleException(MessageP4RequestErrorHandler.java:512)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:161)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:54)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$5(SimpleConnectionManager.java:571)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:589)
	at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.listOpenedFilesChanges(ConnectCommandRunner.java:1021)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$listOpenedFilesChanges$29(ConnectCommandRunner.java:336)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$0(SimpleConnectionManager.java:123)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:156)
	... 10 more

**Desktop (please complete the following information):**
 - OS: Windows 10, 
 - IDE and version: Intellij 2019.2.3 build 193.6015.39
 - Version 1903 OS Build 18362.592

**Comment by groboclown** [comment]
This may have been from a compile with jdk 11 in jdk8 compatibility mode.  The latest release was compiled with jdk 8, so this should help keep this from being an issue.

**Comment by groboclown** [comment]
Turns out this was an issue related to #210.

**Comment by groboclown** [comment]
Based on the similar issue #210 which has been closed, I'm closing this one off, too.
