### ISSUE TITLE
Multiple Work-Spaces (streams) support 

### ISSUE THREAD

**Issue by alexcomsa** [groboclown/p4ic4idea#209]
**Is your feature request related to a problem? Please describe.**
Support working with multiple work spaces , currently if you have multiple work-spaces the plugin  generates an exception if the p4 cli is not set to the one you want to work with .

**Describe the solution you'd like**
I want to be able to manipulate multiple work-spaces without manually executing the 
 p4 set P4CLIENT=myClient command .
**Describe alternatives you've considered**
I run the the CLI command p4 set P4CLIENT=myClient 
**Additional context**
If the current P4CLIENT is set to client1 and I want to work on a different work space the plugin generates the following exceptions 
```
net.groboclown.p4.server.api.P4CommandRunner$ServerResultException:C:/my/new/workspace... - must create client '_____CLIENT_UNSET_____' to access local files.
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.createServerResultException(P4RequestErrorHandler.java:131)
	at net.groboclown.p4.server.impl.connection.impl.MessageP4RequestErrorHandler.handleException(MessageP4RequestErrorHandler.java:411)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:161)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:70)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$6(SimpleConnectionManager.java:575)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:589)
	at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.perforce.p4java.exception.RequestException:C:/my/new/workspace... - must create client '_____CLIENT_UNSET_____' to access local files.
	at net.groboclown.p4.server.impl.connection.impl.MessageStatusUtil.throwIf(MessageStatusUtil.java:48)
	at net.groboclown.p4.server.impl.connection.impl.P4CommandUtil.getFilesDetails(P4CommandUtil.java:430)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$listFilesDetails$40(ConnectCommandRunner.java:450)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$2(SimpleConnectionManager.java:150)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:156)
	... 10 more
```

Also I have tried to create a P4CONFIG for the new work-space (stream) and I get the following exception 
``` 
 WARN - nnection.P4RequestErrorHandler - Running an action with the Perforce server client:{perforce-host:prot@stream} generated an error. 
com.perforce.p4java.exception.ConfigException: Client does not exist: MY/NEW-CLIENT
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$0(SimpleConnectionManager.java:117)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:156)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:54)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$5(SimpleConnectionManager.java:571)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:589)
	at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by groboclown** [comment]
I'm seeing a few other issues around the multi-workspace functionality with the 201 version of the IDE.  I'll dig into these along with this issue.

**Comment by groboclown** [comment]
I found a major issue around the association of the VCS root directory with the configuration, stemming from a misinterpretation of the data given to the configuration panel.

I don't know if this will fix this specific issue, but it's at least a start in the right direction.

**Comment by groboclown** [comment]
Please respond back if this fixes the issue, or if you're still experiencing problems.

**Comment by groboclown** [comment]
There was another bug related to this found after this release - the configuration incorrectly maps the wrong configuration to a root path when loading a project.  The work-around is to edit the configuration.  A fix will be out shortly.
