### ISSUE TITLE
Android Studio 3.6.1 can't open project anymore

### ISSUE THREAD

**Issue by Christian01234** [groboclown/p4ic4idea#212]
After updating Android Studio from version 3.5.3 to 3.6.1 I can not open my project anymore.
After disabling the perforce plugin I can open the project again.
When I start Android Studio from console with studio.bat and enabled perforce plugin, I get the following stack trace when I try to open my project:

2020-03-02 13:01:06,485 [   4108]  ERROR - m.PlatformProjectOpenProcessor - Fatal error initializing plugin PerforceIC
com.intellij.ide.plugins.MainRunner$StartupAbortedException: Fatal error initializing plugin PerforceIC
        at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:122)
        at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:33)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:520)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
        at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:264)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:289)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:604)
        at com.intellij.platform.PlatformProjectOpenProcessor.tryLoadProject(PlatformProjectOpenProcessor.java:280)
        at com.intellij.platform.PlatformProjectOpenProcessor.prepareAndOpenProject(PlatformProjectOpenProcessor.java:254)
        at com.intellij.platform.PlatformProjectOpenProcessor.lambda$doOpenProject$0(PlatformProjectOpenProcessor.java:198)
        at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:253)
        at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
        at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:447)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:552)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.diagnostic.PluginException: Subscription to p4ic4idea:user selected a server to go offline already exists [Plugin: PerforceIC]
        ... 25 more
Caused by: java.lang.IllegalStateException: Subscription to p4ic4idea:user selected a server to go offline already exists
        at com.intellij.util.messages.impl.MessageBusConnectionImpl.subscribe(MessageBusConnectionImpl.java:39)
        at net.groboclown.p4.server.api.messagebus.MessageBusClient$ProjectClient.add(MessageBusClient.java:33)
        at net.groboclown.p4.server.api.messagebus.ProjectMessage.addListener(ProjectMessage.java:57)
        at net.groboclown.p4.server.api.messagebus.UserSelectedOfflineMessage.addListener(UserSelectedOfflineMessage.java:63)
        at net.groboclown.p4.server.api.ProjectConfigRegistry.initComponent(ProjectConfigRegistry.java:227)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
        ... 22 more
2020-03-02 13:01:06,490 [   4113]  ERROR - m.PlatformProjectOpenProcessor - Android Studio 3.6.1  Build #AI-192.7142.36.36.6241897
2020-03-02 13:01:06,493 [   4116]  ERROR - m.PlatformProjectOpenProcessor - JDK: 1.8.0_212-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o
2020-03-02 13:01:06,494 [   4117]  ERROR - m.PlatformProjectOpenProcessor - OS: Windows 10
2020-03-02 13:01:06,499 [   4122]  ERROR - m.PlatformProjectOpenProcessor - Plugin to blame: Perforce IDEA Community Integration version: 0.10.14
2020-03-02 13:01:06,499 [   4122]  ERROR - m.PlatformProjectOpenProcessor - Last Action:
2020-03-02 13:01:06,917 [   4540]   WARN - llij.ide.plugins.PluginManager - Cucumber for Java not loaded: until build 192.7142.36 < AI-192.7142.36.36.6241897
2020-03-02 13:01:06,918 [   4541]   WARN - llij.ide.plugins.PluginManager - Cucumber for Groovy not loaded: until build 192.7142.36 < AI-192.7142.36.36.6241897
2020-03-02 13:01:06,925 [   4548]   WARN - llij.ide.plugins.PluginManager - Rookout not loaded: until build 192.7142.36 < AI-192.7142.36.36.6241897

**Comment by groboclown** [comment]
Thanks for the bug report.  Looks like bit of code duplication snuck in, that other versions of the IDE didn't report as an error.

**Comment by groboclown** [comment]
The fix is now available in release 0.10.16.  Please close this ticket if it works for you, or post the new error message if it still fails.

**Comment by Christian01234** [comment]
With version 0.10.16 it is working again.
Thank you very much! That's so awesome!
