### ISSUE TITLE
Local Changed Diff View for Edited File Generates "null file spec in arguments"

### ISSUE THREAD

**Issue by groboclown** [groboclown/p4ic4idea#213]
**Describe the bug**

**To Reproduce**
1. Open a file for edit in Perforce.
2. Navigate to the VCS panel "Local Changes"
3. Select the file that is open for edit.
4. IDE reports error "P4 Plugin Error: Internal error: null file spec in arguments".  The diff panel also reports the same problem.  The logs show:

```
java.lang.IllegalArgumentException: null file spec in arguments
	at net.groboclown.p4.server.impl.util.FileSpecBuildUtil.replaceDepotRevisions(FileSpecBuildUtil.java:127)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$null$34(ConnectCommandRunner.java:420)
	at net.groboclown.p4.server.api.commands.file.GetFileContentsQuery.when(GetFileContentsQuery.java:61)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$getFileContents$37(ConnectCommandRunner.java:401)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$0(SimpleConnectionManager.java:124)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:157)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:55)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$5(SimpleConnectionManager.java:578)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:596)
	at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE and version: IntelliJ 20.1.1 rc1 (201.7223.58)
 - Version 0.10.16

**Comment by groboclown** [comment]
Fixed.
