### ISSUE TITLE
no such file error for files in different path in a stream

### ISSUE THREAD

**Issue by aaron-mar** [groboclown/p4ic4idea#221]
Getting an warning for files that are in depot paths in the stream definition view.

Using: 
Env: windows 10
Intellij: Community 2020.2, Build IC-202.6397.94
Perforce IDEA Community Integration: 0.11.0

**To Reproduce**
1. In perforce, create a stream with multiple paths in the view. In this case:
       //apps/ml/... apps/...
       //apps/ml/libs/... libs/...
       //depot/projects/grp/common/models/ml/... libs/grp/models/...
2. Load up the stream into a workspace in perforce
3. Create an intellij project
4. Selectively add some of the paths in as maven projects (didn't want to add the whole workspace in)
5. Create a new CL and set it as the active one in the perforce plubin
6. Edit a file in the apps (these are ok)
7. Edit a file in the libs/grp/models (ie. the //depot/projects/grp/common/models/ml/... one at the end of the above list)
8. Notice that an error comes out
9. The diff screen under "Local Changes" shows an error saying:

//apps/ml/libs/grp/models/src/main/java/com/my/company/models/ModelEntity.java#1 - no such file(s).

The event log shows:
6:02 PM	Perforce Server Warning: //apps/ml/libs/grp/models/src/main/java/com/my/company/models/ModelEntity.java#1 - no such file(s). (code s:6/g:17/c:375)

and the following exception shows up in the log:

2020-08-20 13:00:18,318 [599772330]   INFO -                             p4 - cmd (12): p4 change -s -o 413559 
2020-08-20 13:00:18,378 [599772390]   INFO -                             p4 - cmd (13): p4 describe -s 413559 
2020-08-20 13:00:18,380 [599772392]   INFO -                             p4 - cmd (14): p4 fstat -Olhp //depot/projects/grp/common/models/ml/src/main/java/com/my/company/models/ModelEntity.java#1 
2020-08-20 13:00:18,382 [599772394]   INFO -                             p4 - cmd (15): p4 fstat -m5000 -edefault -Rc -Ro -Ol -Op -Oh //amar-ml/... 
2020-08-20 13:00:18,385 [599772397]   INFO - onnection.ConnectCommandRunner - Finished listOpenedFilesChanges; started at Thu Aug 20 13:00:18 PDT 2020, ended at Thu Aug 20 13:00:18 PDT 2020 
2020-08-20 13:00:18,386 [599772398]   INFO - gin.extension.P4ChangeProvider - Processing changes for [D:/dev/ml/libs/grp/models/src/main/java/com/my/company/models/ModelEntity.java] under file://D:/dev/ml 
2020-08-20 13:00:18,389 [599772401]   INFO -                             p4 - cmd (1): p4 info 
2020-08-20 13:00:18,391 [599772403]   INFO -                             p4 - cmd (2): p4 client -o amar-ml 
2020-08-20 13:00:18,396 [599772408]   INFO -                             p4 - cmd (3): p4 where D:/dev/ml/libs/grp/models/src/main/java/com/my/company/models/ModelEntity.java 
2020-08-20 13:00:18,398 [599772410]   INFO -                             p4 - cmd (4): p4 print -q //apps/ml/libs/grp/models/src/main/java/com/my/company/models/ModelEntity.java#1 
2020-08-20 13:00:18,400 [599772412]   WARN - nnection.P4RequestErrorHandler - Running an action with the Perforce server client:my-p4fos.company.my.com:1666@amar-ml generated an error. 
com.perforce.p4java.exception.RequestException: //apps/ml/libs/grp/models/src/main/java/com/my/company/models/ModelEntity.java#1 - no such file(s).
	at com.perforce.p4java.impl.mapbased.server.cmd.ResultMapParser.handleWarnings(ResultMapParser.java:229)
	at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execStreamCmd(NtsServerImpl.java:558)
	at com.perforce.p4java.impl.mapbased.rpc.NtsServerImpl.execStreamCmd(NtsServerImpl.java:478)
	at com.perforce.p4java.impl.mapbased.server.cmd.BaseDelegator.execStreamCmd(BaseDelegator.java:166)
	at com.perforce.p4java.impl.mapbased.server.cmd.PrintDelegator.getFileContents(PrintDelegator.java:56)
	at com.perforce.p4java.impl.mapbased.server.Server.getFileContents(Server.java:2290)
	at net.groboclown.p4.server.impl.connection.impl.P4CommandUtil.loadContents(P4CommandUtil.java:459)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$null$34(ConnectCommandRunner.java:430)
	at net.groboclown.p4.server.api.commands.file.GetFileContentsQuery.when(GetFileContentsQuery.java:70)
	at net.groboclown.p4.server.impl.connection.ConnectCommandRunner.lambda$getFileContents$37(ConnectCommandRunner.java:403)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$null$0(SimpleConnectionManager.java:125)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handleConnection(P4RequestErrorHandler.java:157)
	at net.groboclown.p4.server.impl.connection.P4RequestErrorHandler.handle(P4RequestErrorHandler.java:55)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$handleAsync$5(SimpleConnectionManager.java:579)
	at net.groboclown.p4.server.impl.connection.impl.SimpleConnectionManager.lambda$startPromise$8(SimpleConnectionManager.java:597)
	at net.groboclown.p4.server.api.async.AsyncAnswer.lambda$background$0(AsyncAnswer.java:49)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

For some reason, it picks the correct file when it does the fstat call in the log (3rd line in the log snippet), but it doesn't use the right file when doing the last line that causes an exception.

**Expected behavior**
No errors should occur.

**Attachments**
See above

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE and version: Community IntelliJ 2020.2, Build IC-202.6397.94
 - Version: 0.11.0

**Comment by mahmadzadeh** [comment]
Yep. Getting the same issue on Intellij community edition plugin version 0.11.0
