### ISSUE TITLE
P4JavaAPI error: fetching jobs can incorrectly parse results

### ISSUE THREAD

**Issue by groboclown** [groboclown/p4ic4idea#33]
IChangelist.getJobs() can throw a RequestException if the resulting map isn't parsed correctly by the underlying P4Java API class.  For example:

```
com.perforce.p4java.exception.RequestException: Error detected at line 31.
Syntax error in 'can'.

	at com.perforce.p4java.impl.mapbased.server.Server.handleErrorStr(Server.java:4989)
	at com.perforce.p4java.impl.mapbased.server.Server.getJob(Server.java:3714)
	at com.perforce.p4java.impl.generic.core.Changelist.getJobs(Changelist.java:426)
```

**Comment by groboclown** [comment]
Extra protections were added around this bug, however the source still needs to be fixed.  It looks like re-implementing the job fetching code is needed.

**Comment by groboclown** [comment]
The problem is actually the *request* to the P4 server, which causes the server to return this error message.  I'm not sure what the source is, but lots of extra code protection is now wrapped around the code.  It's probably an issue with a bad job ID being passed.
