### ISSUE TITLE
"Add file" while disconnected causes NPE

### ISSUE THREAD

**Issue by groboclown** [groboclown/p4ic4idea#35]
While working in offline mode, if you attempt to add a file, the plugin generates an NPE.

```
WARN - clown.idea.p4ic.ui.ErrorDialog - Something threw an invalid exception without being properly wrapped 
java.lang.NullPointerException
	at net.groboclown.idea.p4ic.extension.P4VFSListener$3.run(P4VFSListener.java:176)
	at net.groboclown.idea.p4ic.background.Background.runInBackground(Background.java:54)
	at net.groboclown.idea.p4ic.extension.P4VFSListener.performAdding(P4VFSListener.java:166)
	at com.intellij.openapi.vcs.VcsVFSListener.executeAdd(VcsVFSListener.java:173)
	at com.intellij.openapi.vcs.VcsVFSListener.executeAdd(VcsVFSListener.java:132)
	at com.intellij.openapi.vcs.VcsVFSListener$MyCommandAdapter.commandFinished(VcsVFSListener.java:505)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.fireCommandFinished(CoreCommandProcessor.java:187)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.finishCommand(CoreCommandProcessor.java:161)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.finishCommand(CommandProcessorImpl.java:54)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:130)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.refactoring.copy.CopyClassesHandler.copyClassesImpl(CopyClassesHandler.java:305)
	at com.intellij.refactoring.copy.CopyClassesHandler.doCopy(CopyClassesHandler.java:229)
	at com.intellij.refactoring.copy.CopyHandler.doCopy(CopyHandler.java:55)
	at com.intellij.ide.CopyPasteDelegator$MyEditable.performDefaultPaste(CopyPasteDelegator.java:168)
	at com.intellij.ide.CopyPasteDelegator$MyEditable.performPaste(CopyPasteDelegator.java:131)
	at com.intellij.ide.actions.PasteAction.actionPerformed(PasteAction.java:42)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:586)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:637)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by groboclown** [comment]
Not sure what the real cause for this was - it seems like there's lots of null checks around that line.  However, extra checks were added that will raise warnings if it's seen again.
