### ISSUE TITLE
Error message "client 'xxx' can only be used from host 'yyy'"

### ISSUE THREAD

**Issue by PlayWithIt** [groboclown/p4ic4idea#61]
I use Android studio 1.3 and tried to setup Perforce connection to my local Perforce server.
- the project was in the IDE before I setup the plugin
- I configured Perforce settings and the check was OK
- when I restart the IDE or try to edit a file I always get the error message shown in the screenshot.

I can use the mentioned workspace normally from P4V, the hostname in the workspace is the name of my local computer (but not "localhost").

The event log is empty.
The workspace I use is a stream based workspace.

After starting the IDE and confirming the error, the tab "local changes" shows properly (!) the contents of all changlists connected to the actual P4 workspace, so the connection is basically OK.

![p4_error](https://cloud.githubusercontent.com/assets/6370303/9027218/ff43e6aa-394c-11e5-8ed5-556d8f5f7789.png)

**Comment by groboclown** [comment]
Thanks for the bug report.  I have started to investigate this.

**Comment by groboclown** [comment]
I am surprised that there isn't a warning message reported in the log file - every error reported in that dialog is logged at the warning level.

This may seem like a dumb question, but just to make sure, is the reported client in the error the client that you use to connect to the server?

**Comment by PlayWithIt** [comment]
I started the IDE from a console, then I see this on the console:

    WARN - clown.idea.p4ic.ui.ErrorDialog - Client 'HomeStation_dev_holger' can only be used from host 'mypc'.
    net.groboclown.idea.p4ic.server.exceptions.P4Exception: Client 'HomeStation_dev_holger' can only be used from host 'mypc'.
        at net.groboclown.idea.p4ic.server.P4Exec.p4RunFor(P4Exec.java:971)
        at net.groboclown.idea.p4ic.server.P4Exec.p4RunFor(P4Exec.java:848)
        at net.groboclown.idea.p4ic.server.P4Exec.runWithClient(P4Exec.java:726)
        at net.groboclown.idea.p4ic.server.P4Exec.getFileSpecsInChangelist(P4Exec.java:420)
        at net.groboclown.idea.p4ic.server.P4Exec.getFilesInChangelist(P4Exec.java:405)
        at net.groboclown.idea.p4ic.server.RawServerExecutor$8.run(RawServerExecutor.java:387)
        at net.groboclown.idea.p4ic.server.RawServerExecutor$8.run(RawServerExecutor.java:384)
        at net.groboclown.idea.p4ic.server.RawServerExecutor.performAction(RawServerExecutor.java:147)
        at net.groboclown.idea.p4ic.server.RawServerExecutor.getFilesInChangelist(RawServerExecutor.java:384)
        at net.groboclown.idea.p4ic.server.ServerExecutor.getFilesInChangelist(ServerExecutor.java:103)
        at net.groboclown.idea.p4ic.changes.P4ChangeListCache.reloadChangeList(P4ChangeListCache.java:344)
        at net.groboclown.idea.p4ic.changes.P4ChangeListCache.addFilesToChangelist(P4ChangeListCache.java:281)
        at net.groboclown.idea.p4ic.changes.P4ChangelistListener$2.run(P4ChangelistListener.java:154)
        at net.groboclown.idea.p4ic.background.Background.runInBackground(Background.java:41)
        at net.groboclown.idea.p4ic.changes.P4ChangelistListener.changesAdded(P4ChangelistListener.java:139)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
        at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
        at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
        at com.sun.proxy.$Proxy57.changesAdded(Unknown Source)
        at com.intellij.openapi.vcs.changes.DelayedNotificator$MyProxyDispatcher$3.run(DelayedNotificator.java:76)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: com.perforce.p4java.exception.RequestException: Client 'HomeStation_dev_holger' can only be used from host 'mypc'.
        at com.perforce.p4java.impl.mapbased.server.Server.handleErrorStr(Server.java:4989)
        at com.perforce.p4java.impl.mapbased.server.Server.getChangelist(Server.java:3018)
        at com.perforce.p4java.impl.mapbased.server.Server.getChangelist(Server.java:2983)
        at net.groboclown.idea.p4ic.server.P4Exec$11.run(P4Exec.java:424)
        at net.groboclown.idea.p4ic.server.P4Exec$11.run(P4Exec.java:420)
        at net.groboclown.idea.p4ic.server.P4Exec$26.run(P4Exec.java:738)
        at net.groboclown.idea.p4ic.server.P4Exec.p4RunFor(P4Exec.java:863)
        ... 30 more

Is there any possibility to trace which p4 command is issued here?
I didn't try a "normal" workspace yet, this workspace has the "stream" parameter set.

**Comment by groboclown** [comment]
The underlying Perforce command is "p4 reopen (filename)".

Here's what's happening:

1. Your client workspace "HomeStation_dev_holger" is setup with the "Host:" line value set to "mypc".  This means that the Perforce server will only allow *non-read* commands when it thinks you're on the computer called "mypc".
2. The P4Java API tries to figure out your computer's hostname, and it calls `java.net.InetAddress.getLocalHost().getHostName()` to discover it.
3. The P4Java API then passes this hostname string to the server, which doesn't match what the server expects, and fails on this changelist altering command.

My guess is that what `java.net.InetAddress.getLocalHost().getHostName()` returns is either the wrong case (on non-Windows systems, the hostname might be case sensitive, but I'm not sure), or is just a wrong value.

To test it out, you can put together a quick Java program to see what's being returned:
```
public class TestHostname {
    public static void main(String[] args) throws Exception {
        System.out.println(java.net.InetAddress.getLocalHost().getHostName());
    }
}
```
If that seems right, you can test it from the command line with `p4 -H (hostname) reopen (filename)`.

I'm working on a fix that will allow you to override the hostname.  In the meantime, you can remove the `Host:` value from your client spec, as that will tell the Perforce server that it shouldn't perform hostname validation for this client.

**Comment by PlayWithIt** [comment]
Result of the hostname is "mypc":

    mypc:/tmp> javac TestHostname.java 
    mypc:/tmp> java TestHostname
    mypc

This is equal to the host field in the workspace.
P4 reopen returns

    p4 -H mypc reopen HomeControl.iml
    //Tinkerforge/HomeStation_dev_3.0/HomeControl/HomeControl.iml#1 - nothing changed

This looks normal.

By the way: why is a reopen necessary? For which file?

**Comment by groboclown** [comment]
As to "why is a reopen necessary" - reopen is the way to move files between changelists.  Based on the error message dialog title ("P4 Synchronize changes (moved)"), the error came from that bit of code.

I'm really scratching my head over the issue you're seeing.  Here are the things I'm guessing that are the problem:
* The Android Studio version of Java might be returning a different value of the hostname.  I seriously doubt it, though.
* The P4Java API is not correctly passing the hostname to the server correctly.  I doubt this one also, as it works fine on other systems.

At least removing the "host" field from the client spec does what it's supposed to do.

I've put together a patch release (0.6.4.1) that has big warning level logging messages that report the hostname that InetAddress returns.  It also allows you to add a 'P4HOST=(hostname)' in a p4config file to override the hostname (you'll need to switch to a p4config file connection in order to try this out).

**Comment by groboclown** [comment]
https://github.com/groboclown/p4ic4idea/releases/tag/0.6.4.1

**Comment by PlayWithIt** [comment]
I updated the plugin, the console now shows this:

    Default client hostname: [mypc.fritz.box]

=> There is a default domain name ...

**Comment by groboclown** [comment]
That's the issue right there.  Something is changing how the JVM reports the hostname.  I'll look into stripping all the domain parts off of the client name, which should fix your issue without you needing to set the host in the p4config file, or altering the host name in your client spec.

Thanks for working through this with me.

**Comment by PlayWithIt** [comment]
You're welcome. I'm happy that I still can use Perforce..

I also noticed that all my P4 environment variables are gone after starting the IDE.
The startup script seems to change more ...

**Comment by groboclown** [comment]
I've seen IDEA clear out the environment variables, too.  Not much to be done about that, unfortunately.

I'm putting this fix into the next release, which should be out soon.

**Comment by groboclown** [comment]
Let me know if you need more help!  And don't forget to change your "host" line back.
