### ISSUE TITLE
annotate not working

### ISSUE THREAD

**Issue by scriptacus** [groboclown/p4ic4idea#86]
Annotate is behaving poorly for me:

1) When I use the annotate option for files in my repo, it always seems to display every line as the latest revision of the file, e.g.:
somename 12/8/2015 #31 *
somename 12/8/2015 #31 *
somename 12/8/2015 #31 *
somename 12/8/2015 #31 *
...

2) The option for Annotate previous revision is greyed out.
3) Choosing "Show Diff" from the right click menu causes an error:
8:04:56 PM Can not load data for show diff
.. and shows a "Messages Annotate" window with nodes saying "Could not find changelist -1"
4) Choosing "Annotate Revision" from the right click menu shows the "Messages Annotate" window with the error:
Error:Path 'C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 15.0.1\bin\null' is not under client's root 'C:\depot'.

**Comment by scriptacus** [comment]
More info:

[ 140125]   WARN - server.connection.AlertManager - Could not find changelist -1 
net.groboclown.idea.p4ic.server.exceptions.P4Exception: Invalid option: -1.
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.p4RunFor(ClientExec.java:562)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.p4RunFor(ClientExec.java:422)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.runWithClient(ClientExec.java:241)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2.getChangelist(P4Exec2.java:143)
	at net.groboclown.idea.p4ic.v2.server.P4Server$25.query(P4Server.java:1029)
	at net.groboclown.idea.p4ic.v2.server.P4Server$25.query(P4Server.java:994)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection$2.perform(ServerConnection.java:174)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer$1.compute(Synchronizer.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:974)
	at net.groboclown.idea.p4ic.v2.server.connection.Synchronizer$ServerSynchronizer$ConnectionSynchronizer.runImmediateAction(Synchronizer.java:167)
	at net.groboclown.idea.p4ic.v2.server.connection.ServerConnection.query(ServerConnection.java:169)
	at net.groboclown.idea.p4ic.v2.server.P4Server.getChangelistForOnline(P4Server.java:994)
	at net.groboclown.idea.p4ic.extension.P4CommittedChangesProvider.getOneList(P4CommittedChangesProvider.java:161)
	at com.intellij.openapi.vcs.actions.ShowDiffFromAnnotation$1.run(ShowDiffFromAnnotation.java:103)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: com.perforce.p4java.exception.RequestException: Invalid option: -1.
	at com.perforce.p4java.impl.mapbased.server.Server.handleErrorStr(Server.java:4858)
	at com.perforce.p4java.impl.mapbased.server.Server.getChangelist(Server.java:2892)
	at com.perforce.p4java.impl.mapbased.server.Server.getChangelist(Server.java:2857)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$2.run(P4Exec2.java:148)
	at net.groboclown.idea.p4ic.v2.server.connection.P4Exec2$2.run(P4Exec2.java:143)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec$1.run(ClientExec.java:253)
	at net.groboclown.idea.p4ic.v2.server.connection.ClientExec.p4RunFor(ClientExec.java:437)
	... 27 more

**Comment by scriptacus** [comment]
If you need further information, let me know (I'm writing my own custom language plugin, so I have intellij running under the debugger most of the time)

**Comment by groboclown** [comment]
Thanks for the detailed bug report.  This looks like a case of a misinterpret action of the p4 api call

**Comment by groboclown** [comment]
#1 was easy to track down.

#4 I was able to reproduce.

#3 looks like you're using the default changelist, and something isn't correctly recognizing it.  I haven't replicated this yet, but that may be the right direction to look at.

#2 I can't reproduce.  Where are you seeing the option appear, and under what circumstances is it happening?

**Comment by groboclown** [comment]
I was able to replicate the -1 changelist issue.  It occurs when the annotation section of the editor is clicked.  This was another API mis-use, but it interestingly tails into the work on the repository history.

**Comment by groboclown** [comment]
There are still a few issues with the annotations, but all of the major issues identified here look to be closed off.  The remaining issues are the setting of the before and after revision, and the diff view.
