### ISSUE TITLE
IntelliJ 16: project configuration causes assertion error when saving settings

### ISSUE THREAD

**Issue by groboclown** [groboclown/p4ic4idea#93]
Running with IntelliJ IDEA 16 EAP 144.2608.

```
null
java.lang.AssertionError
	at net.groboclown.idea.p4ic.config.P4ConfigProject.announceBaseConfigUpdated(P4ConfigProject.java:120)
	at net.groboclown.idea.p4ic.ui.config.P4ConfigurationProjectPanel.saveSettings(P4ConfigurationProjectPanel.java:61)
	at net.groboclown.idea.p4ic.ui.config.P4ProjectConfigurable.apply(P4ProjectConfigurable.java:62)
	at com.intellij.openapi.vcs.configurable.LazyConfigurable.apply(LazyConfigurable.java:41)
	at com.intellij.openapi.vcs.configurable.VcsConfigurationsDialog.doOKAction(VcsConfigurationsDialog.java:152)

```

**Comment by groboclown** [comment]
This is that same, old issue that has been hounding the configuration panel.  For now, if you reopen the panel and try again, it will save correctly.

**Comment by groboclown** [comment]
I'm not seeing it anymore.
